[package]
name = "risio"
version = "0.1.2"
edition = "2024"
description = "Rust wrapper for ImageStreamIO library"
license = "Unlicense"
repository = "https://github.com/jcranney/risio"


[build-dependencies]
cmake = "0.1.58"
bindgen = "0.72.1"

[dependencies]
anyhow = "1.0.102"
enum-iterator = "2.3.0"
libc = "0.2.186"
memmap2 = "0.9.11"
pyo3 = "0.29.0"
rkyv = "0.8.16"
thiserror = "2.0.18"

[lib]
name = "risio"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "risio-test"
