[package]
name = "risio"
version = "0.1.1"
edition = "2024"
description = "Rust wrapper for ImageStreamIO library"
license = "unlicense"
repository = "https://github.com/jcranney/risio"


[build-dependencies]
cmake = "0.1.58"
bindgen = "0.72.1"

[dependencies]
anyhow = "1.0.102"
enum-iterator = "2.3.0"
thiserror = "2.0.18"

[[bin]]
name = "example_thread"
