[project]
name = "risio"
dynamic = [ "version" ]
requires-python = ">=3.13"
description = "Python interface for Rust wrapper of libImageStreamIO"
readme = "README.md"
license-files = [ "UNLICENSE" ]
license = "Unlicense"
dependencies = [
    "astropy>=7.2.0",
    "maturin>=1.14.0",
    "pybind11>=3.0.4",
    "pymilk",
    "pyqt5>=5.15.11",
    "rich>=15.0.0",
    "shmview>=0.0.10",
    "xaosim>=1.0.11",
]
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 3 - Beta",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  "License :: OSI Approved :: The Unlicense (Unlicense)",
  "Programming Language :: Rust",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]


[project.urls]
Repository = "https://github.com/jcranney/risio"

[tool.uv.sources]
pymilk = { git = "https://github.com/milk-org/pyMilk.git" }

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
include = [{ path = "path/**/*", format = "sdist" }]
