/* initially generated by rust-bindgen 0.72.1, modified inplace by hand. It's possible
to regenerate with bindgen by removing comments in build.rs, but care needs to
be taken in comparing the diff. */

pub const IMAGESTRUCT_VERSION: &[u8; 4] = b"2.00";

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
#[derive(PartialEq, Copy, Clone, Hash, Debug, Default)]
#[repr(C)]
struct __BindgenComplex<T> {
    pub re: T,
    pub im: T,
}
pub const STRINGMAXLEN_IMAGE_NAME: u32 = 80;
const _SEMAPHORE_H: u32 = 1;
const _FEATURES_H: u32 = 1;
const _DEFAULT_SOURCE: u32 = 1;
const __GLIBC_USE_ISOC2Y: u32 = 0;
const __GLIBC_USE_ISOC23: u32 = 0;
const __USE_ISOC11: u32 = 1;
const __USE_ISOC99: u32 = 1;
const __USE_ISOC95: u32 = 1;
const __USE_POSIX_IMPLICITLY: u32 = 1;
const _POSIX_SOURCE: u32 = 1;
const _POSIX_C_SOURCE: u32 = 200809;
const __USE_POSIX: u32 = 1;
const __USE_POSIX2: u32 = 1;
const __USE_POSIX199309: u32 = 1;
const __USE_POSIX199506: u32 = 1;
const __USE_XOPEN2K: u32 = 1;
const __USE_XOPEN2K8: u32 = 1;
const _ATFILE_SOURCE: u32 = 1;
const __WORDSIZE: u32 = 64;
const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
const __SYSCALL_WORDSIZE: u32 = 64;
const __TIMESIZE: u32 = 64;
const __USE_TIME_BITS64: u32 = 1;
const __USE_MISC: u32 = 1;
const __USE_ATFILE: u32 = 1;
const __USE_FORTIFY_LEVEL: u32 = 0;
const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
const __GLIBC_USE_C23_STRTOL: u32 = 0;
const _STDC_PREDEF_H: u32 = 1;
const __STDC_IEC_559__: u32 = 1;
const __STDC_IEC_60559_BFP__: u32 = 201404;
const __STDC_IEC_559_COMPLEX__: u32 = 1;
const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
const __STDC_ISO_10646__: u32 = 201706;
const __GNU_LIBRARY__: u32 = 6;
const __GLIBC__: u32 = 2;
const __GLIBC_MINOR__: u32 = 42;
const _SYS_CDEFS_H: u32 = 1;
const __glibc_c99_flexarr_available: u32 = 1;
const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
const __HAVE_GENERIC_SELECTION: u32 = 1;
const _SYS_TYPES_H: u32 = 1;
const _BITS_TYPES_H: u32 = 1;
const _BITS_TYPESIZES_H: u32 = 1;
const __OFF_T_MATCHES_OFF64_T: u32 = 1;
const __INO_T_MATCHES_INO64_T: u32 = 1;
const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
const __STATFS_MATCHES_STATFS64: u32 = 1;
const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
const __FD_SETSIZE: u32 = 1024;
const _BITS_TIME64_H: u32 = 1;
const __clock_t_defined: u32 = 1;
const __clockid_t_defined: u32 = 1;
const __time_t_defined: u32 = 1;
const __timer_t_defined: u32 = 1;
const _BITS_STDINT_INTN_H: u32 = 1;
const __BIT_TYPES_DEFINED__: u32 = 1;
const _ENDIAN_H: u32 = 1;
const _BITS_ENDIAN_H: u32 = 1;
const __LITTLE_ENDIAN: u32 = 1234;
const __BIG_ENDIAN: u32 = 4321;
const __PDP_ENDIAN: u32 = 3412;
const _BITS_ENDIANNESS_H: u32 = 1;
const __BYTE_ORDER: u32 = 1234;
const __FLOAT_WORD_ORDER: u32 = 1234;
const _BITS_BYTESWAP_H: u32 = 1;
const _BITS_UINTN_IDENTITY_H: u32 = 1;
const _SYS_SELECT_H: u32 = 1;
const __sigset_t_defined: u32 = 1;
const __timeval_defined: u32 = 1;
const _STRUCT_TIMESPEC: u32 = 1;
const _BITS_PTHREADTYPES_COMMON_H: u32 = 1;
const _THREAD_SHARED_TYPES_H: u32 = 1;
const _BITS_PTHREADTYPES_ARCH_H: u32 = 1;
const __SIZEOF_PTHREAD_MUTEX_T: u32 = 40;
const __SIZEOF_PTHREAD_ATTR_T: u32 = 56;
const __SIZEOF_PTHREAD_RWLOCK_T: u32 = 56;
const __SIZEOF_PTHREAD_BARRIER_T: u32 = 32;
const __SIZEOF_PTHREAD_MUTEXATTR_T: u32 = 4;
const __SIZEOF_PTHREAD_COND_T: u32 = 48;
const __SIZEOF_PTHREAD_CONDATTR_T: u32 = 4;
const __SIZEOF_PTHREAD_RWLOCKATTR_T: u32 = 8;
const __SIZEOF_PTHREAD_BARRIERATTR_T: u32 = 4;
const _THREAD_MUTEX_INTERNAL_H: u32 = 1;
const __PTHREAD_MUTEX_HAVE_PREV: u32 = 1;
const __have_pthread_attr_t: u32 = 1;
const __SIZEOF_SEM_T: u32 = 32;
const _STDINT_H: u32 = 1;
const __GLIBC_USE_LIB_EXT2: u32 = 0;
const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
const _BITS_WCHAR_H: u32 = 1;
const _BITS_STDINT_UINTN_H: u32 = 1;
const _BITS_STDINT_LEAST_H: u32 = 1;
const _STDIO_H: u32 = 1;
const _____fpos_t_defined: u32 = 1;
const ____mbstate_t_defined: u32 = 1;
const _____fpos64_t_defined: u32 = 1;
const ____FILE_defined: u32 = 1;
const __FILE_defined: u32 = 1;
const __struct_FILE_defined: u32 = 1;
const _IO_EOF_SEEN: u32 = 16;
const _IO_ERR_SEEN: u32 = 32;
const _IO_USER_LOCK: u32 = 32768;
const __cookie_io_functions_t_defined: u32 = 1;
const _IOFBF: u32 = 0;
const _IOLBF: u32 = 1;
const _IONBF: u32 = 2;
const _BITS_STDIO_LIM_H: u32 = 1;
const __HAVE_FLOAT128: u32 = 1;
const __HAVE_DISTINCT_FLOAT128: u32 = 1;
const __HAVE_FLOAT64X: u32 = 1;
const __HAVE_FLOAT64X_LONG_DOUBLE: u32 = 1;
const __HAVE_FLOAT16: u32 = 0;
const __HAVE_FLOAT32: u32 = 1;
const __HAVE_FLOAT64: u32 = 1;
const __HAVE_FLOAT32X: u32 = 1;
const __HAVE_FLOAT128X: u32 = 0;
const __HAVE_DISTINCT_FLOAT16: u32 = 0;
const __HAVE_DISTINCT_FLOAT32: u32 = 0;
const __HAVE_DISTINCT_FLOAT64: u32 = 0;
const __HAVE_DISTINCT_FLOAT32X: u32 = 0;
const __HAVE_DISTINCT_FLOAT64X: u32 = 0;
const __HAVE_DISTINCT_FLOAT128X: u32 = 0;
const __HAVE_FLOATN_NOT_TYPEDEF: u32 = 0;
const _STDLIB_H: u32 = 1;
const __WNOTHREAD: u32 = 536870912;
const __WALL: u32 = 1073741824;
const __WCLONE: u32 = 2147483648;
const __W_CONTINUED: u32 = 65535;
const __WCOREFLAG: u32 = 128;
const __ldiv_t_defined: u32 = 1;
const __lldiv_t_defined: u32 = 1;
const _ALLOCA_H: u32 = 1;
const _UNISTD_H: u32 = 1;
const _POSIX_VERSION: u32 = 200809;
const __POSIX2_THIS_VERSION: u32 = 200809;
const _POSIX2_VERSION: u32 = 200809;
const _POSIX2_C_VERSION: u32 = 200809;
const _POSIX2_C_BIND: u32 = 200809;
const _POSIX2_C_DEV: u32 = 200809;
const _POSIX2_SW_DEV: u32 = 200809;
const _POSIX2_LOCALEDEF: u32 = 200809;
const _XOPEN_VERSION: u32 = 700;
const _XOPEN_XCU_VERSION: u32 = 4;
const _XOPEN_XPG2: u32 = 1;
const _XOPEN_XPG3: u32 = 1;
const _XOPEN_XPG4: u32 = 1;
const _XOPEN_UNIX: u32 = 1;
const _XOPEN_ENH_I18N: u32 = 1;
const _XOPEN_LEGACY: u32 = 1;
const _BITS_POSIX_OPT_H: u32 = 1;
const _POSIX_JOB_CONTROL: u32 = 1;
const _POSIX_SAVED_IDS: u32 = 1;
const _POSIX_PRIORITY_SCHEDULING: u32 = 200809;
const _POSIX_SYNCHRONIZED_IO: u32 = 200809;
const _POSIX_FSYNC: u32 = 200809;
const _POSIX_MAPPED_FILES: u32 = 200809;
const _POSIX_MEMLOCK: u32 = 200809;
const _POSIX_MEMLOCK_RANGE: u32 = 200809;
const _POSIX_MEMORY_PROTECTION: u32 = 200809;
const _POSIX_CHOWN_RESTRICTED: u32 = 0;
const _POSIX_VDISABLE: u8 = 0u8;
const _POSIX_NO_TRUNC: u32 = 1;
const _XOPEN_REALTIME: u32 = 1;
const _XOPEN_REALTIME_THREADS: u32 = 1;
const _XOPEN_SHM: u32 = 1;
const _POSIX_THREADS: u32 = 200809;
const _POSIX_REENTRANT_FUNCTIONS: u32 = 1;
const _POSIX_THREAD_SAFE_FUNCTIONS: u32 = 200809;
const _POSIX_THREAD_PRIORITY_SCHEDULING: u32 = 200809;
const _POSIX_THREAD_ATTR_STACKSIZE: u32 = 200809;
const _POSIX_THREAD_ATTR_STACKADDR: u32 = 200809;
const _POSIX_THREAD_PRIO_INHERIT: u32 = 200809;
const _POSIX_THREAD_PRIO_PROTECT: u32 = 200809;
const _POSIX_THREAD_ROBUST_PRIO_INHERIT: u32 = 200809;
const _POSIX_THREAD_ROBUST_PRIO_PROTECT: i32 = -1;
const _POSIX_SEMAPHORES: u32 = 200809;
const _POSIX_REALTIME_SIGNALS: u32 = 200809;
const _POSIX_ASYNCHRONOUS_IO: u32 = 200809;
const _POSIX_ASYNC_IO: u32 = 1;
const _LFS_ASYNCHRONOUS_IO: u32 = 1;
const _POSIX_PRIORITIZED_IO: u32 = 200809;
const _LFS64_ASYNCHRONOUS_IO: u32 = 1;
const _LFS_LARGEFILE: u32 = 1;
const _LFS64_LARGEFILE: u32 = 1;
const _LFS64_STDIO: u32 = 1;
const _POSIX_SHARED_MEMORY_OBJECTS: u32 = 200809;
const _POSIX_CPUTIME: u32 = 0;
const _POSIX_THREAD_CPUTIME: u32 = 0;
const _POSIX_REGEXP: u32 = 1;
const _POSIX_READER_WRITER_LOCKS: u32 = 200809;
const _POSIX_SHELL: u32 = 1;
const _POSIX_TIMEOUTS: u32 = 200809;
const _POSIX_SPIN_LOCKS: u32 = 200809;
const _POSIX_SPAWN: u32 = 200809;
const _POSIX_TIMERS: u32 = 200809;
const _POSIX_BARRIERS: u32 = 200809;
const _POSIX_MESSAGE_PASSING: u32 = 200809;
const _POSIX_THREAD_PROCESS_SHARED: u32 = 200809;
const _POSIX_MONOTONIC_CLOCK: u32 = 0;
const _POSIX_CLOCK_SELECTION: u32 = 200809;
const _POSIX_ADVISORY_INFO: u32 = 200809;
const _POSIX_IPV6: u32 = 200809;
const _POSIX_RAW_SOCKETS: u32 = 200809;
const _POSIX2_CHAR_TERM: u32 = 200809;
const _POSIX_SPORADIC_SERVER: i32 = -1;
const _POSIX_THREAD_SPORADIC_SERVER: i32 = -1;
const _POSIX_TRACE: i32 = -1;
const _POSIX_TRACE_EVENT_FILTER: i32 = -1;
const _POSIX_TRACE_INHERIT: i32 = -1;
const _POSIX_TRACE_LOG: i32 = -1;
const _POSIX_TYPED_MEMORY_OBJECTS: i32 = -1;
const _POSIX_V7_LPBIG_OFFBIG: i32 = -1;
const _POSIX_V6_LPBIG_OFFBIG: i32 = -1;
const _XBS5_LPBIG_OFFBIG: i32 = -1;
const _POSIX_V7_LP64_OFF64: u32 = 1;
const _POSIX_V6_LP64_OFF64: u32 = 1;
const _XBS5_LP64_OFF64: u32 = 1;
const __ILP32_OFF32_CFLAGS: &[u8; 5] = b"-m32\0";
const __ILP32_OFF32_LDFLAGS: &[u8; 5] = b"-m32\0";
const __ILP32_OFFBIG_CFLAGS: &[u8; 48] = b"-m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64\0";
const __ILP32_OFFBIG_LDFLAGS: &[u8; 5] = b"-m32\0";
const __LP64_OFF64_CFLAGS: &[u8; 5] = b"-m64\0";
const __LP64_OFF64_LDFLAGS: &[u8; 5] = b"-m64\0";
const _GETOPT_POSIX_H: u32 = 1;
const _GETOPT_CORE_H: u32 = 1;
const _TIME_H: u32 = 1;
const _BITS_TIME_H: u32 = 1;
pub const CLOCK_TAI: u32 = 11;
const __struct_tm_defined: u32 = 1;
const __itimerspec_defined: u32 = 1;
const _BITS_TYPES_LOCALE_T_H: u32 = 1;
const _BITS_TYPES___LOCALE_T_H: u32 = 1;
pub const SEMAPHORE_INITVAL: u32 = 0;
pub const IMAGE_NB_SEMAPHORE: u32 = 10;
pub const IMAGE_NB_PROCTRACE: u32 = 10;
const _DATATYPE_UNINITIALIZED: u32 = 0;
const _DATATYPE_UINT8: u32 = 1;
const _DATATYPE_INT8: u32 = 2;
const _DATATYPE_UINT16: u32 = 3;
const _DATATYPE_INT16: u32 = 4;
const _DATATYPE_UINT32: u32 = 5;
const _DATATYPE_INT32: u32 = 6;
const _DATATYPE_UINT64: u32 = 7;
const _DATATYPE_INT64: u32 = 8;
const _DATATYPE_HALF: u32 = 13;
const _DATATYPE_FLOAT: u32 = 9;
const _DATATYPE_DOUBLE: u32 = 10;
const _DATATYPE_COMPLEX_FLOAT: u32 = 11;
const _DATATYPE_COMPLEX_DOUBLE: u32 = 12;
const _DATATYPE_EVENT_UI8_UI8_UI16_UI8: u32 = 20;
pub const ZAXIS_UNDEF: u32 = 0;
pub const ZAXIS_SPACIAL: u32 = 65536;
pub const ZAXIS_TEMPORAL: u32 = 131072;
pub const ZAXIS_WAVELENGTH: u32 = 196608;
pub const ZAXIS_MAPPING: u32 = 262144;
type __u_char = ::std::os::raw::c_uchar;
type __u_short = ::std::os::raw::c_ushort;
type __u_int = ::std::os::raw::c_uint;
type __u_long = ::std::os::raw::c_ulong;
type __int8_t = ::std::os::raw::c_schar;
type __uint8_t = ::std::os::raw::c_uchar;
type __int16_t = ::std::os::raw::c_short;
type __uint16_t = ::std::os::raw::c_ushort;
type __int32_t = ::std::os::raw::c_int;
type __uint32_t = ::std::os::raw::c_uint;
type __int64_t = ::std::os::raw::c_long;
type __uint64_t = ::std::os::raw::c_ulong;
type __int_least8_t = __int8_t;
type __uint_least8_t = __uint8_t;
type __int_least16_t = __int16_t;
type __uint_least16_t = __uint16_t;
type __int_least32_t = __int32_t;
type __uint_least32_t = __uint32_t;
type __int_least64_t = __int64_t;
type __uint_least64_t = __uint64_t;
type __quad_t = ::std::os::raw::c_long;
type __u_quad_t = ::std::os::raw::c_ulong;
type __intmax_t = ::std::os::raw::c_long;
type __uintmax_t = ::std::os::raw::c_ulong;
type __dev_t = ::std::os::raw::c_ulong;
type __uid_t = ::std::os::raw::c_uint;
type __gid_t = ::std::os::raw::c_uint;
type __ino_t = ::std::os::raw::c_ulong;
type __ino64_t = ::std::os::raw::c_ulong;
type __mode_t = ::std::os::raw::c_uint;
type __nlink_t = ::std::os::raw::c_ulong;
type __off_t = ::std::os::raw::c_long;
type __off64_t = ::std::os::raw::c_long;
type __pid_t = ::std::os::raw::c_int;
type __clock_t = ::std::os::raw::c_long;
type __rlim_t = ::std::os::raw::c_ulong;
type __rlim64_t = ::std::os::raw::c_ulong;
type __id_t = ::std::os::raw::c_uint;
type __time_t = ::std::os::raw::c_long;
type __useconds_t = ::std::os::raw::c_uint;
type __suseconds_t = ::std::os::raw::c_long;
type __suseconds64_t = ::std::os::raw::c_long;
type __daddr_t = ::std::os::raw::c_int;
type __key_t = ::std::os::raw::c_int;
type __clockid_t = ::std::os::raw::c_int;
type __timer_t = *mut ::std::os::raw::c_void;
type __blksize_t = ::std::os::raw::c_long;
type __blkcnt_t = ::std::os::raw::c_long;
type __blkcnt64_t = ::std::os::raw::c_long;
type __fsblkcnt_t = ::std::os::raw::c_ulong;
type __fsblkcnt64_t = ::std::os::raw::c_ulong;
type __fsfilcnt_t = ::std::os::raw::c_ulong;
type __fsfilcnt64_t = ::std::os::raw::c_ulong;
type __fsword_t = ::std::os::raw::c_long;
type __ssize_t = ::std::os::raw::c_long;
type __syscall_slong_t = ::std::os::raw::c_long;
type __syscall_ulong_t = ::std::os::raw::c_ulong;
type __loff_t = __off64_t;
type __caddr_t = *mut ::std::os::raw::c_char;
type __intptr_t = ::std::os::raw::c_long;
type __socklen_t = ::std::os::raw::c_uint;
type __sig_atomic_t = ::std::os::raw::c_int;
pub type ino_t = __ino_t;
pub type pid_t = __pid_t;
pub type timespec = libc::timespec;
pub type sem_t = libc::sem_t;
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timespec"][::std::mem::size_of::<timespec>() - 16usize];
    ["Alignment of timespec"][::std::mem::align_of::<timespec>() - 8usize];
    ["Offset of field: timespec::tv_sec"][::std::mem::offset_of!(timespec, tv_sec) - 0usize];
    ["Offset of field: timespec::tv_nsec"][::std::mem::offset_of!(timespec, tv_nsec) - 8usize];
};

type cudaIpcMemHandle_t = [::std::os::raw::c_char; 64usize];
#[doc = " @brief  Keyword\n The IMAGE_KEYWORD structure includes :\n \t- name\n \t- type\n \t- value"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct IMAGE_KEYWORD {
    #[doc = "< keyword name"]
    name: [::std::os::raw::c_char; 16usize],
    #[doc = "< N: unused, L: long, D: double, S: 16-char string"]
    type_: ::std::os::raw::c_char,
    value: IMAGE_KEYWORD__bindgen_ty_1,
    cnt: u64,
    comment: [::std::os::raw::c_char; 80usize],
}

impl Default for IMAGE_KEYWORD {
    fn default() -> Self {
        Self::new()
    }
}

impl IMAGE_KEYWORD {
    pub fn new() -> Self {
        Self {
            name: [0; 16usize],
            type_: 'N' as i8,
            value: IMAGE_KEYWORD__bindgen_ty_1 { numl: 0 },
            cnt: 0,
            comment: [0; 80usize],
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone)]
union IMAGE_KEYWORD__bindgen_ty_1 {
    numl: i64,
    numf: f64,
    valstr: [::std::os::raw::c_char; 16usize],
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_KEYWORD__bindgen_ty_1"]
        [::std::mem::size_of::<IMAGE_KEYWORD__bindgen_ty_1>() - 16usize];
    ["Alignment of IMAGE_KEYWORD__bindgen_ty_1"]
        [::std::mem::align_of::<IMAGE_KEYWORD__bindgen_ty_1>() - 8usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::numl"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, numl) - 0usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::numf"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, numf) - 0usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::valstr"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, valstr) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_KEYWORD"][::std::mem::size_of::<IMAGE_KEYWORD>() - 128usize];
    ["Alignment of IMAGE_KEYWORD"][::std::mem::align_of::<IMAGE_KEYWORD>() - 8usize];
    ["Offset of field: IMAGE_KEYWORD::name"][::std::mem::offset_of!(IMAGE_KEYWORD, name) - 0usize];
    ["Offset of field: IMAGE_KEYWORD::type_"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, type_) - 16usize];
    ["Offset of field: IMAGE_KEYWORD::value"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, value) - 24usize];
    ["Offset of field: IMAGE_KEYWORD::cnt"][::std::mem::offset_of!(IMAGE_KEYWORD, cnt) - 40usize];
    ["Offset of field: IMAGE_KEYWORD::comment"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, comment) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct complex_float {
    re: f32,
    im: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of complex_float"][::std::mem::size_of::<complex_float>() - 8usize];
    ["Alignment of complex_float"][::std::mem::align_of::<complex_float>() - 4usize];
    ["Offset of field: complex_float::re"][::std::mem::offset_of!(complex_float, re) - 0usize];
    ["Offset of field: complex_float::im"][::std::mem::offset_of!(complex_float, im) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct complex_double {
    re: f64,
    im: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of complex_double"][::std::mem::size_of::<complex_double>() - 16usize];
    ["Alignment of complex_double"][::std::mem::align_of::<complex_double>() - 8usize];
    ["Offset of field: complex_double::re"][::std::mem::offset_of!(complex_double, re) - 0usize];
    ["Offset of field: complex_double::im"][::std::mem::offset_of!(complex_double, im) - 8usize];
};

///
/// Image metadata
///
#[repr(C)]
#[derive(Debug, Clone)]
pub struct IMAGE_METADATA {
    pub version: [::std::os::raw::c_char; 32usize],
    #[doc = " @brief Image Name"]
    pub name: [::std::os::raw::c_char; 80usize],
    #[doc = " @brief Number of axis\n\n @warning 1, 2 or 3. Values above 3 not supported."]
    pub naxis: u8,
    #[doc = " @brief Image size along each axis\n\n  If naxis = 1 (1D image), size[1] and size[2] are irrelevant"]
    pub size: [u32; 3usize],
    #[doc = " @brief Number of elements in image\n\n This is computed upon image creation"]
    pub nelement: u64,
    #[doc = " @brief Data type\n\n Encoded according to data type defines.\n  -  1: uint8_t\n \t-  2: int8_t\n \t-  3: uint16_t\n \t-  4: int16_t\n \t-  5: uint32_t\n \t-  6: int32_t\n \t-  7: uint64_t\n \t-  8: int64_t\n \t-  9: IEEE 754 single-precision binary floating-point format: binary32\n  - 10: IEEE 754 double-precision binary floating-point format: binary64\n  - 11: complex_float\n  - 12: complex double\n  - 13: half precision floating-point\n"]
    pub datatype: u8,
    #[doc = "< image type"]
    pub imagetype: u64,
    pub creationtime: timespec,
    pub lastaccesstime: timespec,
    pub atime: timespec,
    pub writetime: timespec,
    #[doc = "< PID of process that created the stream (if shared = 1)"]
    pub creatorPID: pid_t,
    #[doc = "< PID of process owning the stream (if shared = 1)"]
    pub ownerPID: pid_t,
    #[doc = "< stream is in shared memory"]
    pub shared: u8,
    #[doc = "< inode nummber if shared memory"]
    pub inode: ino_t,
    #[doc = "< -1 if in CPU memory, >=0 if in GPU memory on `location` device"]
    pub location: i8,
    #[doc = "< 1 to log image (default); 0 : do not log: 2 : stop log (then goes back to 2)"]
    pub status: u8,
    #[doc = "< bitmask, encodes read/write permissions.... NOTE: enum instead of defines"]
    pub flag: u64,
    #[doc = "< set to 1 to start logging"]
    pub logflag: u8,
    #[doc = "< number of semaphores supported, specified at image creation"]
    pub sem: u16,
    #[doc = "< number of streamproctrace entries"]
    pub NBproctrace: u16,
    #[doc = "< counter (incremented if image is updated)"]
    pub cnt0: u64,
    #[doc = "< in 3D rolling buffer image, this is the last slice written"]
    pub cnt1: u64,
    #[doc = "< in cnt2-based syncronization, proceed until cnt0=cnt2"]
    pub cnt2: u64,
    #[doc = "< 1 if image is being written"]
    pub write: u8,
    #[doc = "< number of keywords (max: 65536)"]
    pub NBkw: u16,
    pub CBsize: u32,
    pub CBindex: u32,
    pub CBcycle: u64,
    pub imdatamemsize: u64,
    pub cudaMemHandle: cudaIpcMemHandle_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_METADATA"][::std::mem::size_of::<IMAGE_METADATA>() - 384usize];
    ["Alignment of IMAGE_METADATA"][::std::mem::align_of::<IMAGE_METADATA>() - 8usize];
    ["Offset of field: IMAGE_METADATA::version"]
        [::std::mem::offset_of!(IMAGE_METADATA, version) - 0usize];
    ["Offset of field: IMAGE_METADATA::name"]
        [::std::mem::offset_of!(IMAGE_METADATA, name) - 32usize];
    ["Offset of field: IMAGE_METADATA::naxis"]
        [::std::mem::offset_of!(IMAGE_METADATA, naxis) - 112usize];
    ["Offset of field: IMAGE_METADATA::size"]
        [::std::mem::offset_of!(IMAGE_METADATA, size) - 116usize];
    ["Offset of field: IMAGE_METADATA::nelement"]
        [::std::mem::offset_of!(IMAGE_METADATA, nelement) - 128usize];
    ["Offset of field: IMAGE_METADATA::datatype"]
        [::std::mem::offset_of!(IMAGE_METADATA, datatype) - 136usize];
    ["Offset of field: IMAGE_METADATA::imagetype"]
        [::std::mem::offset_of!(IMAGE_METADATA, imagetype) - 144usize];
    ["Offset of field: IMAGE_METADATA::creationtime"]
        [::std::mem::offset_of!(IMAGE_METADATA, creationtime) - 152usize];
    ["Offset of field: IMAGE_METADATA::lastaccesstime"]
        [::std::mem::offset_of!(IMAGE_METADATA, lastaccesstime) - 168usize];
    ["Offset of field: IMAGE_METADATA::atime"]
        [::std::mem::offset_of!(IMAGE_METADATA, atime) - 184usize];
    ["Offset of field: IMAGE_METADATA::writetime"]
        [::std::mem::offset_of!(IMAGE_METADATA, writetime) - 200usize];
    ["Offset of field: IMAGE_METADATA::creatorPID"]
        [::std::mem::offset_of!(IMAGE_METADATA, creatorPID) - 216usize];
    ["Offset of field: IMAGE_METADATA::ownerPID"]
        [::std::mem::offset_of!(IMAGE_METADATA, ownerPID) - 220usize];
    ["Offset of field: IMAGE_METADATA::shared"]
        [::std::mem::offset_of!(IMAGE_METADATA, shared) - 224usize];
    ["Offset of field: IMAGE_METADATA::inode"]
        [::std::mem::offset_of!(IMAGE_METADATA, inode) - 232usize];
    ["Offset of field: IMAGE_METADATA::location"]
        [::std::mem::offset_of!(IMAGE_METADATA, location) - 240usize];
    ["Offset of field: IMAGE_METADATA::status"]
        [::std::mem::offset_of!(IMAGE_METADATA, status) - 241usize];
    ["Offset of field: IMAGE_METADATA::flag"]
        [::std::mem::offset_of!(IMAGE_METADATA, flag) - 248usize];
    ["Offset of field: IMAGE_METADATA::logflag"]
        [::std::mem::offset_of!(IMAGE_METADATA, logflag) - 256usize];
    ["Offset of field: IMAGE_METADATA::sem"]
        [::std::mem::offset_of!(IMAGE_METADATA, sem) - 258usize];
    ["Offset of field: IMAGE_METADATA::NBproctrace"]
        [::std::mem::offset_of!(IMAGE_METADATA, NBproctrace) - 260usize];
    ["Offset of field: IMAGE_METADATA::cnt0"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt0) - 264usize];
    ["Offset of field: IMAGE_METADATA::cnt1"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt1) - 272usize];
    ["Offset of field: IMAGE_METADATA::cnt2"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt2) - 280usize];
    ["Offset of field: IMAGE_METADATA::write"]
        [::std::mem::offset_of!(IMAGE_METADATA, write) - 288usize];
    ["Offset of field: IMAGE_METADATA::NBkw"]
        [::std::mem::offset_of!(IMAGE_METADATA, NBkw) - 290usize];
    ["Offset of field: IMAGE_METADATA::CBsize"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBsize) - 292usize];
    ["Offset of field: IMAGE_METADATA::CBindex"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBindex) - 296usize];
    ["Offset of field: IMAGE_METADATA::CBcycle"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBcycle) - 304usize];
    ["Offset of field: IMAGE_METADATA::imdatamemsize"]
        [::std::mem::offset_of!(IMAGE_METADATA, imdatamemsize) - 312usize];
    ["Offset of field: IMAGE_METADATA::cudaMemHandle"]
        [::std::mem::offset_of!(IMAGE_METADATA, cudaMemHandle) - 320usize];
};
#[doc = " @brief STREAM_PROC_TRACE holds trigger and timing info\n\n Array of STREAM_PROC_TRACE is held within streams to track history.\n This information is assembled by a process, and then written to\n all streams it writes.\n"]
#[repr(C)]
#[derive(Debug, Clone)]
pub struct STREAM_PROC_TRACE {
    triggermode: ::std::os::raw::c_int,
    #[doc = "< PID of process writing stream. 0 if no entry"]
    procwrite_PID: pid_t,
    #[doc = "< trigger stream inode"]
    trigger_inode: ino_t,
    #[doc = "< timestamp process triggered"]
    ts_procstart: timespec,
    #[doc = "< timestamp write this stream"]
    ts_streamupdate: timespec,
    #[doc = "< trigger semaphore"]
    trigsemindex: ::std::os::raw::c_int,
    triggerstatus: ::std::os::raw::c_int,
    #[doc = "< trigger stream cnt0 value at trigger"]
    cnt0: u64,
}

impl Default for STREAM_PROC_TRACE {
    fn default() -> Self {
        Self::new()
    }
}

impl STREAM_PROC_TRACE {
    pub fn new() -> Self {
        Self {
            triggermode: 0, // TODO: This is not explicitly set in the C code
            procwrite_PID: 0,
            trigger_inode: 0,
            ts_procstart: timespec{ tv_sec: 0, tv_nsec: 0},
            ts_streamupdate: timespec{ tv_sec: 0, tv_nsec: 0},
            trigsemindex: -1,
            triggerstatus: 0, // TODO: This is not explicitly set in the C code,
            cnt0: 0,
        }
    }
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of STREAM_PROC_TRACE"][::std::mem::size_of::<STREAM_PROC_TRACE>() - 64usize];
    ["Alignment of STREAM_PROC_TRACE"][::std::mem::align_of::<STREAM_PROC_TRACE>() - 8usize];
    ["Offset of field: STREAM_PROC_TRACE::triggermode"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, triggermode) - 0usize];
    ["Offset of field: STREAM_PROC_TRACE::procwrite_PID"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, procwrite_PID) - 4usize];
    ["Offset of field: STREAM_PROC_TRACE::trigger_inode"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, trigger_inode) - 8usize];
    ["Offset of field: STREAM_PROC_TRACE::ts_procstart"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, ts_procstart) - 16usize];
    ["Offset of field: STREAM_PROC_TRACE::ts_streamupdate"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, ts_streamupdate) - 32usize];
    ["Offset of field: STREAM_PROC_TRACE::trigsemindex"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, trigsemindex) - 48usize];
    ["Offset of field: STREAM_PROC_TRACE::triggerstatus"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, triggerstatus) - 52usize];
    ["Offset of field: STREAM_PROC_TRACE::cnt0"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, cnt0) - 56usize];
};
#[doc = " @brief CBFRAMEMD fast access circular buffer metadata"]
#[repr(C)]
#[derive(Debug, Clone)]
pub struct CBFRAMEMD {
    cnt0: u64,
    cnt1: u64,
    atime: timespec,
    writetime: timespec,
}
impl Default for CBFRAMEMD {
    fn default() -> Self {
        Self::new()
    }
}

impl CBFRAMEMD {
    pub fn new() -> Self {
        Self {
            cnt0: 0,
            cnt1: 0,
            atime: timespec{ tv_sec: 0, tv_nsec: 0},
            writetime: timespec{ tv_sec: 0, tv_nsec: 0},
        }
    }
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CBFRAMEMD"][::std::mem::size_of::<CBFRAMEMD>() - 48usize];
    ["Alignment of CBFRAMEMD"][::std::mem::align_of::<CBFRAMEMD>() - 8usize];
    ["Offset of field: CBFRAMEMD::cnt0"][::std::mem::offset_of!(CBFRAMEMD, cnt0) - 0usize];
    ["Offset of field: CBFRAMEMD::cnt1"][::std::mem::offset_of!(CBFRAMEMD, cnt1) - 8usize];
    ["Offset of field: CBFRAMEMD::atime"][::std::mem::offset_of!(CBFRAMEMD, atime) - 16usize];
    ["Offset of field: CBFRAMEMD::writetime"]
        [::std::mem::offset_of!(CBFRAMEMD, writetime) - 32usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SEMFILEDATA {
    pub semdata: sem_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SEMFILEDATA"][::std::mem::size_of::<SEMFILEDATA>() - 32usize];
    ["Alignment of SEMFILEDATA"][::std::mem::align_of::<SEMFILEDATA>() - 8usize];
    ["Offset of field: SEMFILEDATA::semdata"]
        [::std::mem::offset_of!(SEMFILEDATA, semdata) - 0usize];
};

/// This is the one-to-one mapping of the C "IMAGE" struct defined in ImageStruct.h.
/// It was generated using bindgen, so I trust that it's correct. Eventually, this
/// will not be needed in the RUST API, since this object is mostly responsible for
/// storing relevant runtime data, and those can be defined in rust. However, there
/// is an argument for keeping this definition, since it would allow calling external
/// C code from rust that interfaces with an "IMAGE" type, or providing rust-written
/// functions for external C packages to interface with.
///
/// Another option would be to define a trait that composes the C object, and then
/// implement that trait on the rust objects.
///
/// Note that the struct parameter comments/documentation also comes from the C
/// library, so the implied implementation may be slightly different in rust.
///  
/// ## From the C library:
/// The IMAGE structure includes:
/// - an array of IMAGE_KEWORD structures
/// - an array of IMAGE_METADATA structures (usually only 1 element)
///
/// IMPORTANT: memory allocations for dynamically allocated arrays need to be
/// included in the memory size computation in ImageStreamIO_createIm_gpu
#[repr(C)]
#[derive()]
pub struct IMAGE {
    /// local name (can be different from name in shared memory)
    pub name: [::std::os::raw::c_char; 80usize],
    /// Image usage flag
    ///  - 1 if image is used
    ///  - 0 otherwise.
    /// 
    /// This flag is used when an array of IMAGE type is held in memory
    /// as a way to store multiple images.
    ///
    /// When an image is freed, the corresponding memory (in array) is freed
    /// and this flag set to zero.
    ///
    /// The active images can be listed by looking for IMAGE[i].used==1 entries.
    pub used: u8,
    /// increments when image is (re)-created
    pub createcnt: i64,
    /// if shared memory, file descriptor
    pub shmfd: i32,
    /// total size in memory if shared
    pub memsize: u64,
    /// pointer to semaphore for logging  (8 bytes on 64-bit system)
    pub semlog: *mut sem_t,
    /// pointer to image metadata
    pub md: *mut IMAGE_METADATA,
    /// pointer to data array
    pub array: IMAGE__bindgen_ty_1,
    /// array of pointers to semaphores   (each 8 bytes on 64-bit system)
    pub semptr: *mut *mut sem_t,
    /// array of image Keywords
    pub kw: *mut IMAGE_KEYWORD,
    /// array of semfiles
    pub semfile: *mut SEMFILEDATA,
    /// PID of process that read shared memory stream
    /// Initialized at 0. Otherwise, when process is waiting on semaphore, its PID is written in this array
    /// The array can be used to look for available semaphores
    pub semReadPID: *mut pid_t,
    /// PID of processes that are posting the semaphores (JC: I guess there should only be one?)
    pub semWritePID: *mut pid_t,
    /// semaphore control, written by writer to control semaphore behavior.
    /// See SEMAPHORE_CONTROL_XXX defines for details
    pub semctrl: *mut u32,
    /// semaphore status, written by readers to report back to stream what is their current status.
    /// See SEMAPHORE_STATUS_XXX defines for details
    pub semstatus: *mut u32,
    // array to keep track of stream history/depedencies
    pub streamproctrace: *mut STREAM_PROC_TRACE,
    /// flag for each slice if needed (depends on imagetype)
    pub flagarray: *mut u64,
    /// For circular buffer: counter array for circular buffer, copy of cnt0 onto slice index
    pub cntarray: *mut u64,
    /// For each slice index: time at which data was acquires/created.
    /// This time CAN be copied from input to output
    pub atimearray: *mut timespec,
    /// For each slice index: time at which data was written.
    /// This time CAN be copied from input to output
    pub writetimearray: *mut timespec,

    /// Circular Buffer (CB) option
    /// if CBsize>0, recent frames are memcpied in circular buffer
    /// recent frames may be accessed in small CB for logging.
    ///
    /// array of CB metadata
    pub CircBuff_md: *mut CBFRAMEMD,
    /// data storage for circ buffer
    pub CBimdata: *mut ::std::os::raw::c_void,
}
#[doc = " @brief data storage array\n\n The array is declared as a union, so that multiple data types can be supported \\n\n\n For 2D image with pixel indices ii (x-axis) and jj (y-axis), the pixel values are stored as array.<TYPE>[ jj * md[0].size[0] + ii ] \\n\n image md[0].size[0] is x-axis size, md[0].size[1] is y-axis size\n\n For 3D image with pixel indices ii (x-axis), jj (y-axis) and kk (z-axis), the pixel values are stored as array.<TYPE>[ kk * md[0].size[1] * md[0].size[0] + jj * md[0].size[0] + ii ] \\n\n image md[0].size[0] is x-axis size, md[0].size[1] is y-axis size, md[0].size[2] is z-axis size\n\n @note Up to this point, all members of the structure have a fixed memory offset to the start point"]
#[repr(C)]
#[derive(Copy, Clone)]
pub union IMAGE__bindgen_ty_1 {
    pub raw: *mut ::std::os::raw::c_void,
    pub UI8: *mut u8,
    pub SI8: *mut i8,
    pub UI16: *mut u16,
    pub SI16: *mut i16,
    pub UI32: *mut u32,
    pub SI32: *mut i32,
    pub UI64: *mut u64,
    pub SI64: *mut i64,
    pub F: *mut f32,
    pub D: *mut f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE__bindgen_ty_1"][::std::mem::size_of::<IMAGE__bindgen_ty_1>() - 8usize];
    ["Alignment of IMAGE__bindgen_ty_1"][::std::mem::align_of::<IMAGE__bindgen_ty_1>() - 8usize];
    ["Offset of field: IMAGE__bindgen_ty_1::raw"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, raw) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI8"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI8) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI8"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI8) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI16"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI16) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI16"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI16) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI32"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI32) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI32"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI32) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI64"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI64) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI64"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI64) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::F"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, F) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::D"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, D) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE"][::std::mem::size_of::<IMAGE>() - 248usize];
    ["Alignment of IMAGE"][::std::mem::align_of::<IMAGE>() - 8usize];
    ["Offset of field: IMAGE::name"][::std::mem::offset_of!(IMAGE, name) - 0usize];
    ["Offset of field: IMAGE::used"][::std::mem::offset_of!(IMAGE, used) - 80usize];
    ["Offset of field: IMAGE::createcnt"][::std::mem::offset_of!(IMAGE, createcnt) - 88usize];
    ["Offset of field: IMAGE::shmfd"][::std::mem::offset_of!(IMAGE, shmfd) - 96usize];
    ["Offset of field: IMAGE::memsize"][::std::mem::offset_of!(IMAGE, memsize) - 104usize];
    ["Offset of field: IMAGE::semlog"][::std::mem::offset_of!(IMAGE, semlog) - 112usize];
    ["Offset of field: IMAGE::md"][::std::mem::offset_of!(IMAGE, md) - 120usize];
    ["Offset of field: IMAGE::array"][::std::mem::offset_of!(IMAGE, array) - 128usize];
    ["Offset of field: IMAGE::semptr"][::std::mem::offset_of!(IMAGE, semptr) - 136usize];
    ["Offset of field: IMAGE::kw"][::std::mem::offset_of!(IMAGE, kw) - 144usize];
    ["Offset of field: IMAGE::semfile"][::std::mem::offset_of!(IMAGE, semfile) - 152usize];
    ["Offset of field: IMAGE::semReadPID"][::std::mem::offset_of!(IMAGE, semReadPID) - 160usize];
    ["Offset of field: IMAGE::semWritePID"][::std::mem::offset_of!(IMAGE, semWritePID) - 168usize];
    ["Offset of field: IMAGE::semctrl"][::std::mem::offset_of!(IMAGE, semctrl) - 176usize];
    ["Offset of field: IMAGE::semstatus"][::std::mem::offset_of!(IMAGE, semstatus) - 184usize];
    ["Offset of field: IMAGE::streamproctrace"]
        [::std::mem::offset_of!(IMAGE, streamproctrace) - 192usize];
    ["Offset of field: IMAGE::flagarray"][::std::mem::offset_of!(IMAGE, flagarray) - 200usize];
    ["Offset of field: IMAGE::cntarray"][::std::mem::offset_of!(IMAGE, cntarray) - 208usize];
    ["Offset of field: IMAGE::atimearray"][::std::mem::offset_of!(IMAGE, atimearray) - 216usize];
    ["Offset of field: IMAGE::writetimearray"]
        [::std::mem::offset_of!(IMAGE, writetimearray) - 224usize];
    ["Offset of field: IMAGE::CircBuff_md"][::std::mem::offset_of!(IMAGE, CircBuff_md) - 232usize];
    ["Offset of field: IMAGE::CBimdata"][::std::mem::offset_of!(IMAGE, CBimdata) - 240usize];
};
