/* initially generated by rust-bindgen 0.72.1, modified inplace by hand. It's possible
to regenerate with bindgen by removing comments in build.rs, but care needs to
be taken in comparing the diff. */

pub const IMAGESTRUCT_VERSION: &[u8; 4] = b"2.00";

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
#[derive(PartialEq, Copy, Clone, Hash, Debug, Default)]
#[repr(C)]
struct __BindgenComplex<T> {
    pub re: T,
    pub im: T,
}
pub const STRINGMAXLEN_IMAGE_NAME: u32 = 80;
pub const CLOCK_TAI: u32 = 11;
pub const SEMAPHORE_INITVAL: u32 = 0;
pub const IMAGE_NB_SEMAPHORE: u32 = 10;
pub const IMAGE_NB_PROCTRACE: u32 = 10;
pub const ZAXIS_UNDEF: u32 = 0;
pub const ZAXIS_SPACIAL: u32 = 65536;
pub const ZAXIS_TEMPORAL: u32 = 131072;
pub const ZAXIS_WAVELENGTH: u32 = 196608;
pub const ZAXIS_MAPPING: u32 = 262144;
pub type ino_t = ::std::os::raw::c_ulong;
pub type pid_t = ::std::os::raw::c_int;
pub type timespec = libc::timespec;
pub type sem_t = libc::sem_t;
type cudaIpcMemHandle_t = [::std::os::raw::c_char; 64usize];

#[doc = " @brief  Keyword\n The IMAGE_KEYWORD structure includes :\n \t- name\n \t- type\n \t- value"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct IMAGE_KEYWORD {
    #[doc = "< keyword name"]
    name: [::std::os::raw::c_char; 16usize],
    #[doc = "< N: unused, L: long, D: double, S: 16-char string"]
    type_: ::std::os::raw::c_char,
    value: IMAGE_KEYWORD__bindgen_ty_1,
    cnt: u64,
    comment: [::std::os::raw::c_char; 80usize],
}

impl Default for IMAGE_KEYWORD {
    fn default() -> Self {
        Self::new()
    }
}

impl IMAGE_KEYWORD {
    pub fn new() -> Self {
        Self {
            name: [0; 16usize],
            type_: 'N' as i8,
            value: IMAGE_KEYWORD__bindgen_ty_1 { numl: 0 },
            cnt: 0,
            comment: [0; 80usize],
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone)]
union IMAGE_KEYWORD__bindgen_ty_1 {
    numl: i64,
    numf: f64,
    valstr: [::std::os::raw::c_char; 16usize],
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_KEYWORD__bindgen_ty_1"]
        [::std::mem::size_of::<IMAGE_KEYWORD__bindgen_ty_1>() - 16usize];
    ["Alignment of IMAGE_KEYWORD__bindgen_ty_1"]
        [::std::mem::align_of::<IMAGE_KEYWORD__bindgen_ty_1>() - 8usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::numl"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, numl) - 0usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::numf"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, numf) - 0usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::valstr"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, valstr) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_KEYWORD"][::std::mem::size_of::<IMAGE_KEYWORD>() - 128usize];
    ["Alignment of IMAGE_KEYWORD"][::std::mem::align_of::<IMAGE_KEYWORD>() - 8usize];
    ["Offset of field: IMAGE_KEYWORD::name"][::std::mem::offset_of!(IMAGE_KEYWORD, name) - 0usize];
    ["Offset of field: IMAGE_KEYWORD::type_"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, type_) - 16usize];
    ["Offset of field: IMAGE_KEYWORD::value"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, value) - 24usize];
    ["Offset of field: IMAGE_KEYWORD::cnt"][::std::mem::offset_of!(IMAGE_KEYWORD, cnt) - 40usize];
    ["Offset of field: IMAGE_KEYWORD::comment"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, comment) - 48usize];
};

///
/// Image metadata
///
#[repr(C)]
#[derive(Debug, Clone)]
pub struct IMAGE_METADATA {
    pub version: [::std::os::raw::c_char; 32usize],
    #[doc = " @brief Image Name"]
    pub name: [::std::os::raw::c_char; 80usize],
    #[doc = " @brief Number of axis\n\n @warning 1, 2 or 3. Values above 3 not supported."]
    pub naxis: u8,
    #[doc = " @brief Image size along each axis\n\n  If naxis = 1 (1D image), size[1] and size[2] are irrelevant"]
    pub size: [u32; 3usize],
    #[doc = " @brief Number of elements in image\n\n This is computed upon image creation"]
    pub nelement: u64,
    #[doc = " @brief Data type\n\n Encoded according to data type defines.\n  -  1: uint8_t\n \t-  2: int8_t\n \t-  3: uint16_t\n \t-  4: int16_t\n \t-  5: uint32_t\n \t-  6: int32_t\n \t-  7: uint64_t\n \t-  8: int64_t\n \t-  9: IEEE 754 single-precision binary floating-point format: binary32\n  - 10: IEEE 754 double-precision binary floating-point format: binary64\n  - 11: complex_float\n  - 12: complex double\n  - 13: half precision floating-point\n"]
    pub datatype: u8,
    #[doc = "< image type"]
    pub imagetype: u64,
    pub creationtime: timespec,
    pub lastaccesstime: timespec,
    pub atime: timespec,
    pub writetime: timespec,
    #[doc = "< PID of process that created the stream (if shared = 1)"]
    pub creatorPID: pid_t,
    #[doc = "< PID of process owning the stream (if shared = 1)"]
    pub ownerPID: pid_t,
    #[doc = "< stream is in shared memory"]
    pub shared: u8,
    #[doc = "< inode nummber if shared memory"]
    pub inode: ino_t,
    #[doc = "< -1 if in CPU memory, >=0 if in GPU memory on `location` device"]
    pub location: i8,
    #[doc = "< 1 to log image (default); 0 : do not log: 2 : stop log (then goes back to 2)"]
    pub status: u8,
    #[doc = "< bitmask, encodes read/write permissions.... NOTE: enum instead of defines"]
    pub flag: u64,
    #[doc = "< set to 1 to start logging"]
    pub logflag: u8,
    #[doc = "< number of semaphores supported, specified at image creation"]
    pub sem: u16,
    #[doc = "< number of streamproctrace entries"]
    pub NBproctrace: u16,
    #[doc = "< counter (incremented if image is updated)"]
    pub cnt0: u64,
    #[doc = "< in 3D rolling buffer image, this is the last slice written"]
    pub cnt1: u64,
    #[doc = "< in cnt2-based syncronization, proceed until cnt0=cnt2"]
    pub cnt2: u64,
    #[doc = "< 1 if image is being written"]
    pub write: u8,
    #[doc = "< number of keywords (max: 65536)"]
    pub NBkw: u16,
    pub CBsize: u32,
    pub CBindex: u32,
    pub CBcycle: u64,
    pub imdatamemsize: u64,
    pub cudaMemHandle: cudaIpcMemHandle_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_METADATA"][::std::mem::size_of::<IMAGE_METADATA>() - 384usize];
    ["Alignment of IMAGE_METADATA"][::std::mem::align_of::<IMAGE_METADATA>() - 8usize];
    ["Offset of field: IMAGE_METADATA::version"]
        [::std::mem::offset_of!(IMAGE_METADATA, version) - 0usize];
    ["Offset of field: IMAGE_METADATA::name"]
        [::std::mem::offset_of!(IMAGE_METADATA, name) - 32usize];
    ["Offset of field: IMAGE_METADATA::naxis"]
        [::std::mem::offset_of!(IMAGE_METADATA, naxis) - 112usize];
    ["Offset of field: IMAGE_METADATA::size"]
        [::std::mem::offset_of!(IMAGE_METADATA, size) - 116usize];
    ["Offset of field: IMAGE_METADATA::nelement"]
        [::std::mem::offset_of!(IMAGE_METADATA, nelement) - 128usize];
    ["Offset of field: IMAGE_METADATA::datatype"]
        [::std::mem::offset_of!(IMAGE_METADATA, datatype) - 136usize];
    ["Offset of field: IMAGE_METADATA::imagetype"]
        [::std::mem::offset_of!(IMAGE_METADATA, imagetype) - 144usize];
    ["Offset of field: IMAGE_METADATA::creationtime"]
        [::std::mem::offset_of!(IMAGE_METADATA, creationtime) - 152usize];
    ["Offset of field: IMAGE_METADATA::lastaccesstime"]
        [::std::mem::offset_of!(IMAGE_METADATA, lastaccesstime) - 168usize];
    ["Offset of field: IMAGE_METADATA::atime"]
        [::std::mem::offset_of!(IMAGE_METADATA, atime) - 184usize];
    ["Offset of field: IMAGE_METADATA::writetime"]
        [::std::mem::offset_of!(IMAGE_METADATA, writetime) - 200usize];
    ["Offset of field: IMAGE_METADATA::creatorPID"]
        [::std::mem::offset_of!(IMAGE_METADATA, creatorPID) - 216usize];
    ["Offset of field: IMAGE_METADATA::ownerPID"]
        [::std::mem::offset_of!(IMAGE_METADATA, ownerPID) - 220usize];
    ["Offset of field: IMAGE_METADATA::shared"]
        [::std::mem::offset_of!(IMAGE_METADATA, shared) - 224usize];
    ["Offset of field: IMAGE_METADATA::inode"]
        [::std::mem::offset_of!(IMAGE_METADATA, inode) - 232usize];
    ["Offset of field: IMAGE_METADATA::location"]
        [::std::mem::offset_of!(IMAGE_METADATA, location) - 240usize];
    ["Offset of field: IMAGE_METADATA::status"]
        [::std::mem::offset_of!(IMAGE_METADATA, status) - 241usize];
    ["Offset of field: IMAGE_METADATA::flag"]
        [::std::mem::offset_of!(IMAGE_METADATA, flag) - 248usize];
    ["Offset of field: IMAGE_METADATA::logflag"]
        [::std::mem::offset_of!(IMAGE_METADATA, logflag) - 256usize];
    ["Offset of field: IMAGE_METADATA::sem"]
        [::std::mem::offset_of!(IMAGE_METADATA, sem) - 258usize];
    ["Offset of field: IMAGE_METADATA::NBproctrace"]
        [::std::mem::offset_of!(IMAGE_METADATA, NBproctrace) - 260usize];
    ["Offset of field: IMAGE_METADATA::cnt0"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt0) - 264usize];
    ["Offset of field: IMAGE_METADATA::cnt1"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt1) - 272usize];
    ["Offset of field: IMAGE_METADATA::cnt2"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt2) - 280usize];
    ["Offset of field: IMAGE_METADATA::write"]
        [::std::mem::offset_of!(IMAGE_METADATA, write) - 288usize];
    ["Offset of field: IMAGE_METADATA::NBkw"]
        [::std::mem::offset_of!(IMAGE_METADATA, NBkw) - 290usize];
    ["Offset of field: IMAGE_METADATA::CBsize"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBsize) - 292usize];
    ["Offset of field: IMAGE_METADATA::CBindex"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBindex) - 296usize];
    ["Offset of field: IMAGE_METADATA::CBcycle"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBcycle) - 304usize];
    ["Offset of field: IMAGE_METADATA::imdatamemsize"]
        [::std::mem::offset_of!(IMAGE_METADATA, imdatamemsize) - 312usize];
    ["Offset of field: IMAGE_METADATA::cudaMemHandle"]
        [::std::mem::offset_of!(IMAGE_METADATA, cudaMemHandle) - 320usize];
};
#[doc = " @brief STREAM_PROC_TRACE holds trigger and timing info\n\n Array of STREAM_PROC_TRACE is held within streams to track history.\n This information is assembled by a process, and then written to\n all streams it writes.\n"]
#[repr(C)]
#[derive(Debug, Clone)]
pub struct STREAM_PROC_TRACE {
    triggermode: ::std::os::raw::c_int,
    #[doc = "< PID of process writing stream. 0 if no entry"]
    procwrite_PID: pid_t,
    #[doc = "< trigger stream inode"]
    trigger_inode: ino_t,
    #[doc = "< timestamp process triggered"]
    ts_procstart: timespec,
    #[doc = "< timestamp write this stream"]
    ts_streamupdate: timespec,
    #[doc = "< trigger semaphore"]
    trigsemindex: ::std::os::raw::c_int,
    triggerstatus: ::std::os::raw::c_int,
    #[doc = "< trigger stream cnt0 value at trigger"]
    cnt0: u64,
}

impl Default for STREAM_PROC_TRACE {
    fn default() -> Self {
        Self::new()
    }
}

impl STREAM_PROC_TRACE {
    pub fn new() -> Self {
        Self {
            triggermode: 0, // TODO: This is not explicitly set in the C code
            procwrite_PID: 0,
            trigger_inode: 0,
            ts_procstart: timespec{ tv_sec: 0, tv_nsec: 0},
            ts_streamupdate: timespec{ tv_sec: 0, tv_nsec: 0},
            trigsemindex: -1,
            triggerstatus: 0, // TODO: This is not explicitly set in the C code,
            cnt0: 0,
        }
    }
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of STREAM_PROC_TRACE"][::std::mem::size_of::<STREAM_PROC_TRACE>() - 64usize];
    ["Alignment of STREAM_PROC_TRACE"][::std::mem::align_of::<STREAM_PROC_TRACE>() - 8usize];
    ["Offset of field: STREAM_PROC_TRACE::triggermode"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, triggermode) - 0usize];
    ["Offset of field: STREAM_PROC_TRACE::procwrite_PID"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, procwrite_PID) - 4usize];
    ["Offset of field: STREAM_PROC_TRACE::trigger_inode"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, trigger_inode) - 8usize];
    ["Offset of field: STREAM_PROC_TRACE::ts_procstart"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, ts_procstart) - 16usize];
    ["Offset of field: STREAM_PROC_TRACE::ts_streamupdate"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, ts_streamupdate) - 32usize];
    ["Offset of field: STREAM_PROC_TRACE::trigsemindex"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, trigsemindex) - 48usize];
    ["Offset of field: STREAM_PROC_TRACE::triggerstatus"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, triggerstatus) - 52usize];
    ["Offset of field: STREAM_PROC_TRACE::cnt0"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, cnt0) - 56usize];
};
#[doc = " @brief CBFRAMEMD fast access circular buffer metadata"]
#[repr(C)]
#[derive(Debug, Clone)]
#[allow(clippy::upper_case_acronyms)]
pub struct CBFRAMEMD {
    cnt0: u64,
    cnt1: u64,
    atime: timespec,
    writetime: timespec,
}
impl Default for CBFRAMEMD {
    fn default() -> Self {
        Self::new()
    }
}

impl CBFRAMEMD {
    pub fn new() -> Self {
        Self {
            cnt0: 0,
            cnt1: 0,
            atime: timespec{ tv_sec: 0, tv_nsec: 0},
            writetime: timespec{ tv_sec: 0, tv_nsec: 0},
        }
    }
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CBFRAMEMD"][::std::mem::size_of::<CBFRAMEMD>() - 48usize];
    ["Alignment of CBFRAMEMD"][::std::mem::align_of::<CBFRAMEMD>() - 8usize];
    ["Offset of field: CBFRAMEMD::cnt0"][::std::mem::offset_of!(CBFRAMEMD, cnt0) - 0usize];
    ["Offset of field: CBFRAMEMD::cnt1"][::std::mem::offset_of!(CBFRAMEMD, cnt1) - 8usize];
    ["Offset of field: CBFRAMEMD::atime"][::std::mem::offset_of!(CBFRAMEMD, atime) - 16usize];
    ["Offset of field: CBFRAMEMD::writetime"]
        [::std::mem::offset_of!(CBFRAMEMD, writetime) - 32usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
#[allow(clippy::upper_case_acronyms)]
pub struct SEMFILEDATA {
    pub semdata: sem_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SEMFILEDATA"][::std::mem::size_of::<SEMFILEDATA>() - 32usize];
    ["Alignment of SEMFILEDATA"][::std::mem::align_of::<SEMFILEDATA>() - 8usize];
    ["Offset of field: SEMFILEDATA::semdata"]
        [::std::mem::offset_of!(SEMFILEDATA, semdata) - 0usize];
};

/// This is the one-to-one mapping of the C "IMAGE" struct defined in ImageStruct.h.
/// It was generated using bindgen, so I trust that it's correct. Eventually, this
/// will not be needed in the RUST API, since this object is mostly responsible for
/// storing relevant runtime data, and those can be defined in rust. However, there
/// is an argument for keeping this definition, since it would allow calling external
/// C code from rust that interfaces with an "IMAGE" type, or providing rust-written
/// functions for external C packages to interface with.
///
/// Another option would be to define a trait that composes the C object, and then
/// implement that trait on the rust objects.
///
/// Note that the struct parameter comments/documentation also comes from the C
/// library, so the implied implementation may be slightly different in rust.
///  
/// ## From the C library:
/// The IMAGE structure includes:
/// - an array of IMAGE_KEWORD structures
/// - an array of IMAGE_METADATA structures (usually only 1 element)
///
/// IMPORTANT: memory allocations for dynamically allocated arrays need to be
/// included in the memory size computation in ImageStreamIO_createIm_gpu
#[repr(C)]
#[derive()]
pub struct IMAGE {
    /// local name (can be different from name in shared memory)
    pub name: [::std::os::raw::c_char; 80usize],
    /// Image usage flag
    ///  - 1 if image is used
    ///  - 0 otherwise.
    /// 
    /// This flag is used when an array of IMAGE type is held in memory
    /// as a way to store multiple images.
    ///
    /// When an image is freed, the corresponding memory (in array) is freed
    /// and this flag set to zero.
    ///
    /// The active images can be listed by looking for IMAGE[i].used==1 entries.
    pub used: u8,
    /// increments when image is (re)-created
    pub createcnt: i64,
    /// if shared memory, file descriptor
    pub shmfd: i32,
    /// total size in memory if shared
    pub memsize: u64,
    /// pointer to semaphore for logging  (8 bytes on 64-bit system)
    pub semlog: *mut sem_t,
    /// pointer to image metadata
    pub md: *mut IMAGE_METADATA,
    /// pointer to data array
    pub array: IMAGE__bindgen_ty_1,
    /// array of pointers to semaphores   (each 8 bytes on 64-bit system)
    pub semptr: *mut *mut sem_t,
    /// array of image Keywords
    pub kw: *mut IMAGE_KEYWORD,
    /// array of semfiles
    pub semfile: *mut SEMFILEDATA,
    /// PID of process that read shared memory stream
    /// Initialized at 0. Otherwise, when process is waiting on semaphore, its PID is written in this array
    /// The array can be used to look for available semaphores
    pub semReadPID: *mut pid_t,
    /// PID of processes that are posting the semaphores (JC: I guess there should only be one?)
    pub semWritePID: *mut pid_t,
    /// semaphore control, written by writer to control semaphore behavior.
    /// See SEMAPHORE_CONTROL_XXX defines for details
    pub semctrl: *mut u32,
    /// semaphore status, written by readers to report back to stream what is their current status.
    /// See SEMAPHORE_STATUS_XXX defines for details
    pub semstatus: *mut u32,
    // array to keep track of stream history/depedencies
    pub streamproctrace: *mut STREAM_PROC_TRACE,
    /// flag for each slice if needed (depends on imagetype)
    pub flagarray: *mut u64,
    /// For circular buffer: counter array for circular buffer, copy of cnt0 onto slice index
    pub cntarray: *mut u64,
    /// For each slice index: time at which data was acquires/created.
    /// This time CAN be copied from input to output
    pub atimearray: *mut timespec,
    /// For each slice index: time at which data was written.
    /// This time CAN be copied from input to output
    pub writetimearray: *mut timespec,

    /// Circular Buffer (CB) option
    /// if CBsize>0, recent frames are memcpied in circular buffer
    /// recent frames may be accessed in small CB for logging.
    ///
    /// array of CB metadata
    pub CircBuff_md: *mut CBFRAMEMD,
    /// data storage for circ buffer
    pub CBimdata: *mut ::std::os::raw::c_void,
}
#[doc = " @brief data storage array\n\n The array is declared as a union, so that multiple data types can be supported \\n\n\n For 2D image with pixel indices ii (x-axis) and jj (y-axis), the pixel values are stored as array.<TYPE>[ jj * md[0].size[0] + ii ] \\n\n image md[0].size[0] is x-axis size, md[0].size[1] is y-axis size\n\n For 3D image with pixel indices ii (x-axis), jj (y-axis) and kk (z-axis), the pixel values are stored as array.<TYPE>[ kk * md[0].size[1] * md[0].size[0] + jj * md[0].size[0] + ii ] \\n\n image md[0].size[0] is x-axis size, md[0].size[1] is y-axis size, md[0].size[2] is z-axis size\n\n @note Up to this point, all members of the structure have a fixed memory offset to the start point"]
#[repr(C)]
#[derive(Copy, Clone)]
pub union IMAGE__bindgen_ty_1 {
    pub raw: *mut ::std::os::raw::c_void,
    pub UI8: *mut u8,
    pub SI8: *mut i8,
    pub UI16: *mut u16,
    pub SI16: *mut i16,
    pub UI32: *mut u32,
    pub SI32: *mut i32,
    pub UI64: *mut u64,
    pub SI64: *mut i64,
    pub F: *mut f32,
    pub D: *mut f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE__bindgen_ty_1"][::std::mem::size_of::<IMAGE__bindgen_ty_1>() - 8usize];
    ["Alignment of IMAGE__bindgen_ty_1"][::std::mem::align_of::<IMAGE__bindgen_ty_1>() - 8usize];
    ["Offset of field: IMAGE__bindgen_ty_1::raw"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, raw) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI8"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI8) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI8"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI8) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI16"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI16) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI16"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI16) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI32"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI32) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI32"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI32) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI64"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI64) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI64"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI64) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::F"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, F) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::D"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, D) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE"][::std::mem::size_of::<IMAGE>() - 248usize];
    ["Alignment of IMAGE"][::std::mem::align_of::<IMAGE>() - 8usize];
    ["Offset of field: IMAGE::name"][::std::mem::offset_of!(IMAGE, name) - 0usize];
    ["Offset of field: IMAGE::used"][::std::mem::offset_of!(IMAGE, used) - 80usize];
    ["Offset of field: IMAGE::createcnt"][::std::mem::offset_of!(IMAGE, createcnt) - 88usize];
    ["Offset of field: IMAGE::shmfd"][::std::mem::offset_of!(IMAGE, shmfd) - 96usize];
    ["Offset of field: IMAGE::memsize"][::std::mem::offset_of!(IMAGE, memsize) - 104usize];
    ["Offset of field: IMAGE::semlog"][::std::mem::offset_of!(IMAGE, semlog) - 112usize];
    ["Offset of field: IMAGE::md"][::std::mem::offset_of!(IMAGE, md) - 120usize];
    ["Offset of field: IMAGE::array"][::std::mem::offset_of!(IMAGE, array) - 128usize];
    ["Offset of field: IMAGE::semptr"][::std::mem::offset_of!(IMAGE, semptr) - 136usize];
    ["Offset of field: IMAGE::kw"][::std::mem::offset_of!(IMAGE, kw) - 144usize];
    ["Offset of field: IMAGE::semfile"][::std::mem::offset_of!(IMAGE, semfile) - 152usize];
    ["Offset of field: IMAGE::semReadPID"][::std::mem::offset_of!(IMAGE, semReadPID) - 160usize];
    ["Offset of field: IMAGE::semWritePID"][::std::mem::offset_of!(IMAGE, semWritePID) - 168usize];
    ["Offset of field: IMAGE::semctrl"][::std::mem::offset_of!(IMAGE, semctrl) - 176usize];
    ["Offset of field: IMAGE::semstatus"][::std::mem::offset_of!(IMAGE, semstatus) - 184usize];
    ["Offset of field: IMAGE::streamproctrace"]
        [::std::mem::offset_of!(IMAGE, streamproctrace) - 192usize];
    ["Offset of field: IMAGE::flagarray"][::std::mem::offset_of!(IMAGE, flagarray) - 200usize];
    ["Offset of field: IMAGE::cntarray"][::std::mem::offset_of!(IMAGE, cntarray) - 208usize];
    ["Offset of field: IMAGE::atimearray"][::std::mem::offset_of!(IMAGE, atimearray) - 216usize];
    ["Offset of field: IMAGE::writetimearray"]
        [::std::mem::offset_of!(IMAGE, writetimearray) - 224usize];
    ["Offset of field: IMAGE::CircBuff_md"][::std::mem::offset_of!(IMAGE, CircBuff_md) - 232usize];
    ["Offset of field: IMAGE::CBimdata"][::std::mem::offset_of!(IMAGE, CBimdata) - 240usize];
};
