/* initially generated by rust-bindgen 0.72.1, modified inplace by hand. It's possible
to regenerate with bindgen by removing comments in build.rs, but care needs to
be taken in comparing the diff. */

pub const IMAGESTRUCT_VERSION: &[u8; 4] = b"2.00";

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
#[derive(PartialEq, Copy, Clone, Hash, Debug, Default)]
#[repr(C)]
struct __BindgenComplex<T> {
    pub re: T,
    pub im: T,
}
pub const STRINGMAXLEN_IMAGE_NAME: u32 = 80;
const _SEMAPHORE_H: u32 = 1;
const _FEATURES_H: u32 = 1;
const _DEFAULT_SOURCE: u32 = 1;
const __GLIBC_USE_ISOC2Y: u32 = 0;
const __GLIBC_USE_ISOC23: u32 = 0;
const __USE_ISOC11: u32 = 1;
const __USE_ISOC99: u32 = 1;
const __USE_ISOC95: u32 = 1;
const __USE_POSIX_IMPLICITLY: u32 = 1;
const _POSIX_SOURCE: u32 = 1;
const _POSIX_C_SOURCE: u32 = 200809;
const __USE_POSIX: u32 = 1;
const __USE_POSIX2: u32 = 1;
const __USE_POSIX199309: u32 = 1;
const __USE_POSIX199506: u32 = 1;
const __USE_XOPEN2K: u32 = 1;
const __USE_XOPEN2K8: u32 = 1;
const _ATFILE_SOURCE: u32 = 1;
const __WORDSIZE: u32 = 64;
const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
const __SYSCALL_WORDSIZE: u32 = 64;
const __TIMESIZE: u32 = 64;
const __USE_TIME_BITS64: u32 = 1;
const __USE_MISC: u32 = 1;
const __USE_ATFILE: u32 = 1;
const __USE_FORTIFY_LEVEL: u32 = 0;
const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
const __GLIBC_USE_C23_STRTOL: u32 = 0;
const _STDC_PREDEF_H: u32 = 1;
const __STDC_IEC_559__: u32 = 1;
const __STDC_IEC_60559_BFP__: u32 = 201404;
const __STDC_IEC_559_COMPLEX__: u32 = 1;
const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
const __STDC_ISO_10646__: u32 = 201706;
const __GNU_LIBRARY__: u32 = 6;
const __GLIBC__: u32 = 2;
const __GLIBC_MINOR__: u32 = 42;
const _SYS_CDEFS_H: u32 = 1;
const __glibc_c99_flexarr_available: u32 = 1;
const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
const __HAVE_GENERIC_SELECTION: u32 = 1;
const _SYS_TYPES_H: u32 = 1;
const _BITS_TYPES_H: u32 = 1;
const _BITS_TYPESIZES_H: u32 = 1;
const __OFF_T_MATCHES_OFF64_T: u32 = 1;
const __INO_T_MATCHES_INO64_T: u32 = 1;
const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
const __STATFS_MATCHES_STATFS64: u32 = 1;
const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
const __FD_SETSIZE: u32 = 1024;
const _BITS_TIME64_H: u32 = 1;
const __clock_t_defined: u32 = 1;
const __clockid_t_defined: u32 = 1;
const __time_t_defined: u32 = 1;
const __timer_t_defined: u32 = 1;
const _BITS_STDINT_INTN_H: u32 = 1;
const __BIT_TYPES_DEFINED__: u32 = 1;
const _ENDIAN_H: u32 = 1;
const _BITS_ENDIAN_H: u32 = 1;
const __LITTLE_ENDIAN: u32 = 1234;
const __BIG_ENDIAN: u32 = 4321;
const __PDP_ENDIAN: u32 = 3412;
const _BITS_ENDIANNESS_H: u32 = 1;
const __BYTE_ORDER: u32 = 1234;
const __FLOAT_WORD_ORDER: u32 = 1234;
const _BITS_BYTESWAP_H: u32 = 1;
const _BITS_UINTN_IDENTITY_H: u32 = 1;
const _SYS_SELECT_H: u32 = 1;
const __sigset_t_defined: u32 = 1;
const __timeval_defined: u32 = 1;
const _STRUCT_TIMESPEC: u32 = 1;
const _BITS_PTHREADTYPES_COMMON_H: u32 = 1;
const _THREAD_SHARED_TYPES_H: u32 = 1;
const _BITS_PTHREADTYPES_ARCH_H: u32 = 1;
const __SIZEOF_PTHREAD_MUTEX_T: u32 = 40;
const __SIZEOF_PTHREAD_ATTR_T: u32 = 56;
const __SIZEOF_PTHREAD_RWLOCK_T: u32 = 56;
const __SIZEOF_PTHREAD_BARRIER_T: u32 = 32;
const __SIZEOF_PTHREAD_MUTEXATTR_T: u32 = 4;
const __SIZEOF_PTHREAD_COND_T: u32 = 48;
const __SIZEOF_PTHREAD_CONDATTR_T: u32 = 4;
const __SIZEOF_PTHREAD_RWLOCKATTR_T: u32 = 8;
const __SIZEOF_PTHREAD_BARRIERATTR_T: u32 = 4;
const _THREAD_MUTEX_INTERNAL_H: u32 = 1;
const __PTHREAD_MUTEX_HAVE_PREV: u32 = 1;
const __have_pthread_attr_t: u32 = 1;
const __SIZEOF_SEM_T: u32 = 32;
const _STDINT_H: u32 = 1;
const __GLIBC_USE_LIB_EXT2: u32 = 0;
const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
const _BITS_WCHAR_H: u32 = 1;
const _BITS_STDINT_UINTN_H: u32 = 1;
const _BITS_STDINT_LEAST_H: u32 = 1;
const _STDIO_H: u32 = 1;
const _____fpos_t_defined: u32 = 1;
const ____mbstate_t_defined: u32 = 1;
const _____fpos64_t_defined: u32 = 1;
const ____FILE_defined: u32 = 1;
const __FILE_defined: u32 = 1;
const __struct_FILE_defined: u32 = 1;
const _IO_EOF_SEEN: u32 = 16;
const _IO_ERR_SEEN: u32 = 32;
const _IO_USER_LOCK: u32 = 32768;
const __cookie_io_functions_t_defined: u32 = 1;
const _IOFBF: u32 = 0;
const _IOLBF: u32 = 1;
const _IONBF: u32 = 2;
const _BITS_STDIO_LIM_H: u32 = 1;
const __HAVE_FLOAT128: u32 = 1;
const __HAVE_DISTINCT_FLOAT128: u32 = 1;
const __HAVE_FLOAT64X: u32 = 1;
const __HAVE_FLOAT64X_LONG_DOUBLE: u32 = 1;
const __HAVE_FLOAT16: u32 = 0;
const __HAVE_FLOAT32: u32 = 1;
const __HAVE_FLOAT64: u32 = 1;
const __HAVE_FLOAT32X: u32 = 1;
const __HAVE_FLOAT128X: u32 = 0;
const __HAVE_DISTINCT_FLOAT16: u32 = 0;
const __HAVE_DISTINCT_FLOAT32: u32 = 0;
const __HAVE_DISTINCT_FLOAT64: u32 = 0;
const __HAVE_DISTINCT_FLOAT32X: u32 = 0;
const __HAVE_DISTINCT_FLOAT64X: u32 = 0;
const __HAVE_DISTINCT_FLOAT128X: u32 = 0;
const __HAVE_FLOATN_NOT_TYPEDEF: u32 = 0;
const _STDLIB_H: u32 = 1;
const __WNOTHREAD: u32 = 536870912;
const __WALL: u32 = 1073741824;
const __WCLONE: u32 = 2147483648;
const __W_CONTINUED: u32 = 65535;
const __WCOREFLAG: u32 = 128;
const __ldiv_t_defined: u32 = 1;
const __lldiv_t_defined: u32 = 1;
const _ALLOCA_H: u32 = 1;
const _UNISTD_H: u32 = 1;
const _POSIX_VERSION: u32 = 200809;
const __POSIX2_THIS_VERSION: u32 = 200809;
const _POSIX2_VERSION: u32 = 200809;
const _POSIX2_C_VERSION: u32 = 200809;
const _POSIX2_C_BIND: u32 = 200809;
const _POSIX2_C_DEV: u32 = 200809;
const _POSIX2_SW_DEV: u32 = 200809;
const _POSIX2_LOCALEDEF: u32 = 200809;
const _XOPEN_VERSION: u32 = 700;
const _XOPEN_XCU_VERSION: u32 = 4;
const _XOPEN_XPG2: u32 = 1;
const _XOPEN_XPG3: u32 = 1;
const _XOPEN_XPG4: u32 = 1;
const _XOPEN_UNIX: u32 = 1;
const _XOPEN_ENH_I18N: u32 = 1;
const _XOPEN_LEGACY: u32 = 1;
const _BITS_POSIX_OPT_H: u32 = 1;
const _POSIX_JOB_CONTROL: u32 = 1;
const _POSIX_SAVED_IDS: u32 = 1;
const _POSIX_PRIORITY_SCHEDULING: u32 = 200809;
const _POSIX_SYNCHRONIZED_IO: u32 = 200809;
const _POSIX_FSYNC: u32 = 200809;
const _POSIX_MAPPED_FILES: u32 = 200809;
const _POSIX_MEMLOCK: u32 = 200809;
const _POSIX_MEMLOCK_RANGE: u32 = 200809;
const _POSIX_MEMORY_PROTECTION: u32 = 200809;
const _POSIX_CHOWN_RESTRICTED: u32 = 0;
const _POSIX_VDISABLE: u8 = 0u8;
const _POSIX_NO_TRUNC: u32 = 1;
const _XOPEN_REALTIME: u32 = 1;
const _XOPEN_REALTIME_THREADS: u32 = 1;
const _XOPEN_SHM: u32 = 1;
const _POSIX_THREADS: u32 = 200809;
const _POSIX_REENTRANT_FUNCTIONS: u32 = 1;
const _POSIX_THREAD_SAFE_FUNCTIONS: u32 = 200809;
const _POSIX_THREAD_PRIORITY_SCHEDULING: u32 = 200809;
const _POSIX_THREAD_ATTR_STACKSIZE: u32 = 200809;
const _POSIX_THREAD_ATTR_STACKADDR: u32 = 200809;
const _POSIX_THREAD_PRIO_INHERIT: u32 = 200809;
const _POSIX_THREAD_PRIO_PROTECT: u32 = 200809;
const _POSIX_THREAD_ROBUST_PRIO_INHERIT: u32 = 200809;
const _POSIX_THREAD_ROBUST_PRIO_PROTECT: i32 = -1;
const _POSIX_SEMAPHORES: u32 = 200809;
const _POSIX_REALTIME_SIGNALS: u32 = 200809;
const _POSIX_ASYNCHRONOUS_IO: u32 = 200809;
const _POSIX_ASYNC_IO: u32 = 1;
const _LFS_ASYNCHRONOUS_IO: u32 = 1;
const _POSIX_PRIORITIZED_IO: u32 = 200809;
const _LFS64_ASYNCHRONOUS_IO: u32 = 1;
const _LFS_LARGEFILE: u32 = 1;
const _LFS64_LARGEFILE: u32 = 1;
const _LFS64_STDIO: u32 = 1;
const _POSIX_SHARED_MEMORY_OBJECTS: u32 = 200809;
const _POSIX_CPUTIME: u32 = 0;
const _POSIX_THREAD_CPUTIME: u32 = 0;
const _POSIX_REGEXP: u32 = 1;
const _POSIX_READER_WRITER_LOCKS: u32 = 200809;
const _POSIX_SHELL: u32 = 1;
const _POSIX_TIMEOUTS: u32 = 200809;
const _POSIX_SPIN_LOCKS: u32 = 200809;
const _POSIX_SPAWN: u32 = 200809;
const _POSIX_TIMERS: u32 = 200809;
const _POSIX_BARRIERS: u32 = 200809;
const _POSIX_MESSAGE_PASSING: u32 = 200809;
const _POSIX_THREAD_PROCESS_SHARED: u32 = 200809;
const _POSIX_MONOTONIC_CLOCK: u32 = 0;
const _POSIX_CLOCK_SELECTION: u32 = 200809;
const _POSIX_ADVISORY_INFO: u32 = 200809;
const _POSIX_IPV6: u32 = 200809;
const _POSIX_RAW_SOCKETS: u32 = 200809;
const _POSIX2_CHAR_TERM: u32 = 200809;
const _POSIX_SPORADIC_SERVER: i32 = -1;
const _POSIX_THREAD_SPORADIC_SERVER: i32 = -1;
const _POSIX_TRACE: i32 = -1;
const _POSIX_TRACE_EVENT_FILTER: i32 = -1;
const _POSIX_TRACE_INHERIT: i32 = -1;
const _POSIX_TRACE_LOG: i32 = -1;
const _POSIX_TYPED_MEMORY_OBJECTS: i32 = -1;
const _POSIX_V7_LPBIG_OFFBIG: i32 = -1;
const _POSIX_V6_LPBIG_OFFBIG: i32 = -1;
const _XBS5_LPBIG_OFFBIG: i32 = -1;
const _POSIX_V7_LP64_OFF64: u32 = 1;
const _POSIX_V6_LP64_OFF64: u32 = 1;
const _XBS5_LP64_OFF64: u32 = 1;
const __ILP32_OFF32_CFLAGS: &[u8; 5] = b"-m32\0";
const __ILP32_OFF32_LDFLAGS: &[u8; 5] = b"-m32\0";
const __ILP32_OFFBIG_CFLAGS: &[u8; 48] = b"-m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64\0";
const __ILP32_OFFBIG_LDFLAGS: &[u8; 5] = b"-m32\0";
const __LP64_OFF64_CFLAGS: &[u8; 5] = b"-m64\0";
const __LP64_OFF64_LDFLAGS: &[u8; 5] = b"-m64\0";
const _GETOPT_POSIX_H: u32 = 1;
const _GETOPT_CORE_H: u32 = 1;
const _TIME_H: u32 = 1;
const _BITS_TIME_H: u32 = 1;
pub const CLOCK_TAI: u32 = 11;
const __struct_tm_defined: u32 = 1;
const __itimerspec_defined: u32 = 1;
const _BITS_TYPES_LOCALE_T_H: u32 = 1;
const _BITS_TYPES___LOCALE_T_H: u32 = 1;
pub const SEMAPHORE_INITVAL: u32 = 0;
pub const IMAGE_NB_SEMAPHORE: u32 = 10;
pub const IMAGE_NB_PROCTRACE: u32 = 10;
const _DATATYPE_UNINITIALIZED: u32 = 0;
const _DATATYPE_UINT8: u32 = 1;
const _DATATYPE_INT8: u32 = 2;
const _DATATYPE_UINT16: u32 = 3;
const _DATATYPE_INT16: u32 = 4;
const _DATATYPE_UINT32: u32 = 5;
const _DATATYPE_INT32: u32 = 6;
const _DATATYPE_UINT64: u32 = 7;
const _DATATYPE_INT64: u32 = 8;
const _DATATYPE_HALF: u32 = 13;
const _DATATYPE_FLOAT: u32 = 9;
const _DATATYPE_DOUBLE: u32 = 10;
const _DATATYPE_COMPLEX_FLOAT: u32 = 11;
const _DATATYPE_COMPLEX_DOUBLE: u32 = 12;
const _DATATYPE_EVENT_UI8_UI8_UI16_UI8: u32 = 20;
pub const ZAXIS_UNDEF: u32 = 0;
pub const ZAXIS_SPACIAL: u32 = 65536;
pub const ZAXIS_TEMPORAL: u32 = 131072;
pub const ZAXIS_WAVELENGTH: u32 = 196608;
pub const ZAXIS_MAPPING: u32 = 262144;
type __u_char = ::std::os::raw::c_uchar;
type __u_short = ::std::os::raw::c_ushort;
type __u_int = ::std::os::raw::c_uint;
type __u_long = ::std::os::raw::c_ulong;
type __int8_t = ::std::os::raw::c_schar;
type __uint8_t = ::std::os::raw::c_uchar;
type __int16_t = ::std::os::raw::c_short;
type __uint16_t = ::std::os::raw::c_ushort;
type __int32_t = ::std::os::raw::c_int;
type __uint32_t = ::std::os::raw::c_uint;
type __int64_t = ::std::os::raw::c_long;
type __uint64_t = ::std::os::raw::c_ulong;
type __int_least8_t = __int8_t;
type __uint_least8_t = __uint8_t;
type __int_least16_t = __int16_t;
type __uint_least16_t = __uint16_t;
type __int_least32_t = __int32_t;
type __uint_least32_t = __uint32_t;
type __int_least64_t = __int64_t;
type __uint_least64_t = __uint64_t;
type __quad_t = ::std::os::raw::c_long;
type __u_quad_t = ::std::os::raw::c_ulong;
type __intmax_t = ::std::os::raw::c_long;
type __uintmax_t = ::std::os::raw::c_ulong;
type __dev_t = ::std::os::raw::c_ulong;
type __uid_t = ::std::os::raw::c_uint;
type __gid_t = ::std::os::raw::c_uint;
type __ino_t = ::std::os::raw::c_ulong;
type __ino64_t = ::std::os::raw::c_ulong;
type __mode_t = ::std::os::raw::c_uint;
type __nlink_t = ::std::os::raw::c_ulong;
type __off_t = ::std::os::raw::c_long;
type __off64_t = ::std::os::raw::c_long;
type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
type __clock_t = ::std::os::raw::c_long;
type __rlim_t = ::std::os::raw::c_ulong;
type __rlim64_t = ::std::os::raw::c_ulong;
type __id_t = ::std::os::raw::c_uint;
type __time_t = ::std::os::raw::c_long;
type __useconds_t = ::std::os::raw::c_uint;
type __suseconds_t = ::std::os::raw::c_long;
type __suseconds64_t = ::std::os::raw::c_long;
type __daddr_t = ::std::os::raw::c_int;
type __key_t = ::std::os::raw::c_int;
type __clockid_t = ::std::os::raw::c_int;
type __timer_t = *mut ::std::os::raw::c_void;
type __blksize_t = ::std::os::raw::c_long;
type __blkcnt_t = ::std::os::raw::c_long;
type __blkcnt64_t = ::std::os::raw::c_long;
type __fsblkcnt_t = ::std::os::raw::c_ulong;
type __fsblkcnt64_t = ::std::os::raw::c_ulong;
type __fsfilcnt_t = ::std::os::raw::c_ulong;
type __fsfilcnt64_t = ::std::os::raw::c_ulong;
type __fsword_t = ::std::os::raw::c_long;
type __ssize_t = ::std::os::raw::c_long;
type __syscall_slong_t = ::std::os::raw::c_long;
type __syscall_ulong_t = ::std::os::raw::c_ulong;
type __loff_t = __off64_t;
type __caddr_t = *mut ::std::os::raw::c_char;
type __intptr_t = ::std::os::raw::c_long;
type __socklen_t = ::std::os::raw::c_uint;
type __sig_atomic_t = ::std::os::raw::c_int;
type ino_t = __ino_t;
pub type pid_t = __pid_t;
type clockid_t = __clockid_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __sigset_t {
    pub __val: [::std::os::raw::c_ulong; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __sigset_t"][::std::mem::size_of::<__sigset_t>() - 128usize];
    ["Alignment of __sigset_t"][::std::mem::align_of::<__sigset_t>() - 8usize];
    ["Offset of field: __sigset_t::__val"][::std::mem::offset_of!(__sigset_t, __val) - 0usize];
};
#[repr(C)]
#[derive(Debug, Clone)]
pub struct timeval {
    pub tv_sec: __time_t,
    pub tv_usec: __suseconds_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timeval"][::std::mem::size_of::<timeval>() - 16usize];
    ["Alignment of timeval"][::std::mem::align_of::<timeval>() - 8usize];
    ["Offset of field: timeval::tv_sec"][::std::mem::offset_of!(timeval, tv_sec) - 0usize];
    ["Offset of field: timeval::tv_usec"][::std::mem::offset_of!(timeval, tv_usec) - 8usize];
};
#[repr(C)]
#[derive(Debug, Clone, PartialEq)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
impl Default for timespec {
    fn default() -> Self {
        Self::new()
    }
}

impl timespec {
    pub fn new() -> Self {
        Self {
            tv_sec: 0,
            tv_nsec: 0,
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timespec"][::std::mem::size_of::<timespec>() - 16usize];
    ["Alignment of timespec"][::std::mem::align_of::<timespec>() - 8usize];
    ["Offset of field: timespec::tv_sec"][::std::mem::offset_of!(timespec, tv_sec) - 0usize];
    ["Offset of field: timespec::tv_nsec"][::std::mem::offset_of!(timespec, tv_nsec) - 8usize];
};
type __fd_mask = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct fd_set {
    pub __fds_bits: [__fd_mask; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fd_set"][::std::mem::size_of::<fd_set>() - 128usize];
    ["Alignment of fd_set"][::std::mem::align_of::<fd_set>() - 8usize];
    ["Offset of field: fd_set::__fds_bits"][::std::mem::offset_of!(fd_set, __fds_bits) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union __atomic_wide_counter {
    pub __value64: ::std::os::raw::c_ulonglong,
    pub __value32: __atomic_wide_counter__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __atomic_wide_counter__bindgen_ty_1 {
    pub __low: ::std::os::raw::c_uint,
    pub __high: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __atomic_wide_counter__bindgen_ty_1"]
        [::std::mem::size_of::<__atomic_wide_counter__bindgen_ty_1>() - 8usize];
    ["Alignment of __atomic_wide_counter__bindgen_ty_1"]
        [::std::mem::align_of::<__atomic_wide_counter__bindgen_ty_1>() - 4usize];
    ["Offset of field: __atomic_wide_counter__bindgen_ty_1::__low"]
        [::std::mem::offset_of!(__atomic_wide_counter__bindgen_ty_1, __low) - 0usize];
    ["Offset of field: __atomic_wide_counter__bindgen_ty_1::__high"]
        [::std::mem::offset_of!(__atomic_wide_counter__bindgen_ty_1, __high) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __atomic_wide_counter"][::std::mem::size_of::<__atomic_wide_counter>() - 8usize];
    ["Alignment of __atomic_wide_counter"]
        [::std::mem::align_of::<__atomic_wide_counter>() - 8usize];
    ["Offset of field: __atomic_wide_counter::__value64"]
        [::std::mem::offset_of!(__atomic_wide_counter, __value64) - 0usize];
    ["Offset of field: __atomic_wide_counter::__value32"]
        [::std::mem::offset_of!(__atomic_wide_counter, __value32) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __pthread_internal_list {
    pub __prev: *mut __pthread_internal_list,
    pub __next: *mut __pthread_internal_list,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __pthread_internal_list"][::std::mem::size_of::<__pthread_internal_list>() - 16usize];
    ["Alignment of __pthread_internal_list"]
        [::std::mem::align_of::<__pthread_internal_list>() - 8usize];
    ["Offset of field: __pthread_internal_list::__prev"]
        [::std::mem::offset_of!(__pthread_internal_list, __prev) - 0usize];
    ["Offset of field: __pthread_internal_list::__next"]
        [::std::mem::offset_of!(__pthread_internal_list, __next) - 8usize];
};
type __pthread_list_t = __pthread_internal_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __pthread_internal_slist {
    __next: *mut __pthread_internal_slist,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __pthread_internal_slist"]
        [::std::mem::size_of::<__pthread_internal_slist>() - 8usize];
    ["Alignment of __pthread_internal_slist"]
        [::std::mem::align_of::<__pthread_internal_slist>() - 8usize];
    ["Offset of field: __pthread_internal_slist::__next"]
        [::std::mem::offset_of!(__pthread_internal_slist, __next) - 0usize];
};
type __pthread_slist_t = __pthread_internal_slist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __pthread_mutex_s {
    __lock: ::std::os::raw::c_int,
    __count: ::std::os::raw::c_uint,
    __owner: ::std::os::raw::c_int,
    __nusers: ::std::os::raw::c_uint,
    __kind: ::std::os::raw::c_int,
    __spins: ::std::os::raw::c_short,
    __elision: ::std::os::raw::c_short,
    __list: __pthread_list_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __pthread_mutex_s"][::std::mem::size_of::<__pthread_mutex_s>() - 40usize];
    ["Alignment of __pthread_mutex_s"][::std::mem::align_of::<__pthread_mutex_s>() - 8usize];
    ["Offset of field: __pthread_mutex_s::__lock"]
        [::std::mem::offset_of!(__pthread_mutex_s, __lock) - 0usize];
    ["Offset of field: __pthread_mutex_s::__count"]
        [::std::mem::offset_of!(__pthread_mutex_s, __count) - 4usize];
    ["Offset of field: __pthread_mutex_s::__owner"]
        [::std::mem::offset_of!(__pthread_mutex_s, __owner) - 8usize];
    ["Offset of field: __pthread_mutex_s::__nusers"]
        [::std::mem::offset_of!(__pthread_mutex_s, __nusers) - 12usize];
    ["Offset of field: __pthread_mutex_s::__kind"]
        [::std::mem::offset_of!(__pthread_mutex_s, __kind) - 16usize];
    ["Offset of field: __pthread_mutex_s::__spins"]
        [::std::mem::offset_of!(__pthread_mutex_s, __spins) - 20usize];
    ["Offset of field: __pthread_mutex_s::__elision"]
        [::std::mem::offset_of!(__pthread_mutex_s, __elision) - 22usize];
    ["Offset of field: __pthread_mutex_s::__list"]
        [::std::mem::offset_of!(__pthread_mutex_s, __list) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __pthread_rwlock_arch_t {
    __readers: ::std::os::raw::c_uint,
    __writers: ::std::os::raw::c_uint,
    __wrphase_futex: ::std::os::raw::c_uint,
    __writers_futex: ::std::os::raw::c_uint,
    __pad3: ::std::os::raw::c_uint,
    __pad4: ::std::os::raw::c_uint,
    __cur_writer: ::std::os::raw::c_int,
    __shared: ::std::os::raw::c_int,
    __rwelision: ::std::os::raw::c_schar,
    __pad1: [::std::os::raw::c_uchar; 7usize],
    __pad2: ::std::os::raw::c_ulong,
    __flags: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __pthread_rwlock_arch_t"][::std::mem::size_of::<__pthread_rwlock_arch_t>() - 56usize];
    ["Alignment of __pthread_rwlock_arch_t"]
        [::std::mem::align_of::<__pthread_rwlock_arch_t>() - 8usize];
    ["Offset of field: __pthread_rwlock_arch_t::__readers"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __readers) - 0usize];
    ["Offset of field: __pthread_rwlock_arch_t::__writers"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __writers) - 4usize];
    ["Offset of field: __pthread_rwlock_arch_t::__wrphase_futex"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __wrphase_futex) - 8usize];
    ["Offset of field: __pthread_rwlock_arch_t::__writers_futex"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __writers_futex) - 12usize];
    ["Offset of field: __pthread_rwlock_arch_t::__pad3"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __pad3) - 16usize];
    ["Offset of field: __pthread_rwlock_arch_t::__pad4"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __pad4) - 20usize];
    ["Offset of field: __pthread_rwlock_arch_t::__cur_writer"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __cur_writer) - 24usize];
    ["Offset of field: __pthread_rwlock_arch_t::__shared"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __shared) - 28usize];
    ["Offset of field: __pthread_rwlock_arch_t::__rwelision"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __rwelision) - 32usize];
    ["Offset of field: __pthread_rwlock_arch_t::__pad1"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __pad1) - 33usize];
    ["Offset of field: __pthread_rwlock_arch_t::__pad2"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __pad2) - 40usize];
    ["Offset of field: __pthread_rwlock_arch_t::__flags"]
        [::std::mem::offset_of!(__pthread_rwlock_arch_t, __flags) - 48usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
struct __pthread_cond_s {
    __wseq: __atomic_wide_counter,
    __g1_start: __atomic_wide_counter,
    __g_size: [::std::os::raw::c_uint; 2usize],
    __g1_orig_size: ::std::os::raw::c_uint,
    __wrefs: ::std::os::raw::c_uint,
    __g_signals: [::std::os::raw::c_uint; 2usize],
    __unused_initialized_1: ::std::os::raw::c_uint,
    __unused_initialized_2: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __pthread_cond_s"][::std::mem::size_of::<__pthread_cond_s>() - 48usize];
    ["Alignment of __pthread_cond_s"][::std::mem::align_of::<__pthread_cond_s>() - 8usize];
    ["Offset of field: __pthread_cond_s::__wseq"]
        [::std::mem::offset_of!(__pthread_cond_s, __wseq) - 0usize];
    ["Offset of field: __pthread_cond_s::__g1_start"]
        [::std::mem::offset_of!(__pthread_cond_s, __g1_start) - 8usize];
    ["Offset of field: __pthread_cond_s::__g_size"]
        [::std::mem::offset_of!(__pthread_cond_s, __g_size) - 16usize];
    ["Offset of field: __pthread_cond_s::__g1_orig_size"]
        [::std::mem::offset_of!(__pthread_cond_s, __g1_orig_size) - 24usize];
    ["Offset of field: __pthread_cond_s::__wrefs"]
        [::std::mem::offset_of!(__pthread_cond_s, __wrefs) - 28usize];
    ["Offset of field: __pthread_cond_s::__g_signals"]
        [::std::mem::offset_of!(__pthread_cond_s, __g_signals) - 32usize];
    ["Offset of field: __pthread_cond_s::__unused_initialized_1"]
        [::std::mem::offset_of!(__pthread_cond_s, __unused_initialized_1) - 40usize];
    ["Offset of field: __pthread_cond_s::__unused_initialized_2"]
        [::std::mem::offset_of!(__pthread_cond_s, __unused_initialized_2) - 44usize];
};
type __tss_t = ::std::os::raw::c_uint;
type __thrd_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __once_flag {
    __data: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __once_flag"][::std::mem::size_of::<__once_flag>() - 4usize];
    ["Alignment of __once_flag"][::std::mem::align_of::<__once_flag>() - 4usize];
    ["Offset of field: __once_flag::__data"][::std::mem::offset_of!(__once_flag, __data) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_mutexattr_t {
    __size: [::std::os::raw::c_char; 4usize],
    __align: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_mutexattr_t"][::std::mem::size_of::<pthread_mutexattr_t>() - 4usize];
    ["Alignment of pthread_mutexattr_t"][::std::mem::align_of::<pthread_mutexattr_t>() - 4usize];
    ["Offset of field: pthread_mutexattr_t::__size"]
        [::std::mem::offset_of!(pthread_mutexattr_t, __size) - 0usize];
    ["Offset of field: pthread_mutexattr_t::__align"]
        [::std::mem::offset_of!(pthread_mutexattr_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_condattr_t {
    __size: [::std::os::raw::c_char; 4usize],
    __align: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_condattr_t"][::std::mem::size_of::<pthread_condattr_t>() - 4usize];
    ["Alignment of pthread_condattr_t"][::std::mem::align_of::<pthread_condattr_t>() - 4usize];
    ["Offset of field: pthread_condattr_t::__size"]
        [::std::mem::offset_of!(pthread_condattr_t, __size) - 0usize];
    ["Offset of field: pthread_condattr_t::__align"]
        [::std::mem::offset_of!(pthread_condattr_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_attr_t {
    __size: [::std::os::raw::c_char; 56usize],
    __align: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_attr_t"][::std::mem::size_of::<pthread_attr_t>() - 56usize];
    ["Alignment of pthread_attr_t"][::std::mem::align_of::<pthread_attr_t>() - 8usize];
    ["Offset of field: pthread_attr_t::__size"]
        [::std::mem::offset_of!(pthread_attr_t, __size) - 0usize];
    ["Offset of field: pthread_attr_t::__align"]
        [::std::mem::offset_of!(pthread_attr_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_mutex_t {
    __data: __pthread_mutex_s,
    __size: [::std::os::raw::c_char; 40usize],
    __align: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_mutex_t"][::std::mem::size_of::<pthread_mutex_t>() - 40usize];
    ["Alignment of pthread_mutex_t"][::std::mem::align_of::<pthread_mutex_t>() - 8usize];
    ["Offset of field: pthread_mutex_t::__data"]
        [::std::mem::offset_of!(pthread_mutex_t, __data) - 0usize];
    ["Offset of field: pthread_mutex_t::__size"]
        [::std::mem::offset_of!(pthread_mutex_t, __size) - 0usize];
    ["Offset of field: pthread_mutex_t::__align"]
        [::std::mem::offset_of!(pthread_mutex_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_cond_t {
    __data: __pthread_cond_s,
    __size: [::std::os::raw::c_char; 48usize],
    __align: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_cond_t"][::std::mem::size_of::<pthread_cond_t>() - 48usize];
    ["Alignment of pthread_cond_t"][::std::mem::align_of::<pthread_cond_t>() - 8usize];
    ["Offset of field: pthread_cond_t::__data"]
        [::std::mem::offset_of!(pthread_cond_t, __data) - 0usize];
    ["Offset of field: pthread_cond_t::__size"]
        [::std::mem::offset_of!(pthread_cond_t, __size) - 0usize];
    ["Offset of field: pthread_cond_t::__align"]
        [::std::mem::offset_of!(pthread_cond_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_rwlock_t {
    __data: __pthread_rwlock_arch_t,
    __size: [::std::os::raw::c_char; 56usize],
    __align: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_rwlock_t"][::std::mem::size_of::<pthread_rwlock_t>() - 56usize];
    ["Alignment of pthread_rwlock_t"][::std::mem::align_of::<pthread_rwlock_t>() - 8usize];
    ["Offset of field: pthread_rwlock_t::__data"]
        [::std::mem::offset_of!(pthread_rwlock_t, __data) - 0usize];
    ["Offset of field: pthread_rwlock_t::__size"]
        [::std::mem::offset_of!(pthread_rwlock_t, __size) - 0usize];
    ["Offset of field: pthread_rwlock_t::__align"]
        [::std::mem::offset_of!(pthread_rwlock_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_rwlockattr_t {
    __size: [::std::os::raw::c_char; 8usize],
    __align: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_rwlockattr_t"][::std::mem::size_of::<pthread_rwlockattr_t>() - 8usize];
    ["Alignment of pthread_rwlockattr_t"][::std::mem::align_of::<pthread_rwlockattr_t>() - 8usize];
    ["Offset of field: pthread_rwlockattr_t::__size"]
        [::std::mem::offset_of!(pthread_rwlockattr_t, __size) - 0usize];
    ["Offset of field: pthread_rwlockattr_t::__align"]
        [::std::mem::offset_of!(pthread_rwlockattr_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_barrier_t {
    __size: [::std::os::raw::c_char; 32usize],
    __align: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_barrier_t"][::std::mem::size_of::<pthread_barrier_t>() - 32usize];
    ["Alignment of pthread_barrier_t"][::std::mem::align_of::<pthread_barrier_t>() - 8usize];
    ["Offset of field: pthread_barrier_t::__size"]
        [::std::mem::offset_of!(pthread_barrier_t, __size) - 0usize];
    ["Offset of field: pthread_barrier_t::__align"]
        [::std::mem::offset_of!(pthread_barrier_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
union pthread_barrierattr_t {
    __size: [::std::os::raw::c_char; 4usize],
    __align: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_barrierattr_t"][::std::mem::size_of::<pthread_barrierattr_t>() - 4usize];
    ["Alignment of pthread_barrierattr_t"]
        [::std::mem::align_of::<pthread_barrierattr_t>() - 4usize];
    ["Offset of field: pthread_barrierattr_t::__size"]
        [::std::mem::offset_of!(pthread_barrierattr_t, __size) - 0usize];
    ["Offset of field: pthread_barrierattr_t::__align"]
        [::std::mem::offset_of!(pthread_barrierattr_t, __align) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union sem_t {
    pub __size: [::std::os::raw::c_char; 32usize],
    pub __align: ::std::os::raw::c_long,
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sem_t"][::std::mem::size_of::<sem_t>() - 32usize];
    ["Alignment of sem_t"][::std::mem::align_of::<sem_t>() - 8usize];
    ["Offset of field: sem_t::__size"][::std::mem::offset_of!(sem_t, __size) - 0usize];
    ["Offset of field: sem_t::__align"][::std::mem::offset_of!(sem_t, __align) - 0usize];
};
unsafe extern "C" {
    pub fn sem_init(
        __sem: *mut sem_t,
        __pshared: ::std::os::raw::c_int,
        __value: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
type __gnuc_va_list = __builtin_va_list;
#[repr(C)]
#[derive(Copy, Clone)]
struct __mbstate_t {
    __count: ::std::os::raw::c_int,
    __value: __mbstate_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
union __mbstate_t__bindgen_ty_1 {
    __wch: ::std::os::raw::c_uint,
    __wchb: [::std::os::raw::c_char; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t__bindgen_ty_1"]
        [::std::mem::size_of::<__mbstate_t__bindgen_ty_1>() - 4usize];
    ["Alignment of __mbstate_t__bindgen_ty_1"]
        [::std::mem::align_of::<__mbstate_t__bindgen_ty_1>() - 4usize];
    ["Offset of field: __mbstate_t__bindgen_ty_1::__wch"]
        [::std::mem::offset_of!(__mbstate_t__bindgen_ty_1, __wch) - 0usize];
    ["Offset of field: __mbstate_t__bindgen_ty_1::__wchb"]
        [::std::mem::offset_of!(__mbstate_t__bindgen_ty_1, __wchb) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 8usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 4usize];
    ["Offset of field: __mbstate_t::__count"]
        [::std::mem::offset_of!(__mbstate_t, __count) - 0usize];
    ["Offset of field: __mbstate_t::__value"]
        [::std::mem::offset_of!(__mbstate_t, __value) - 4usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
struct _G_fpos_t {
    __pos: __off_t,
    __state: __mbstate_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _G_fpos_t"][::std::mem::size_of::<_G_fpos_t>() - 16usize];
    ["Alignment of _G_fpos_t"][::std::mem::align_of::<_G_fpos_t>() - 8usize];
    ["Offset of field: _G_fpos_t::__pos"][::std::mem::offset_of!(_G_fpos_t, __pos) - 0usize];
    ["Offset of field: _G_fpos_t::__state"][::std::mem::offset_of!(_G_fpos_t, __state) - 8usize];
};
type __fpos_t = _G_fpos_t;
#[repr(C)]
#[derive(Copy, Clone)]
struct _G_fpos64_t {
    __pos: __off64_t,
    __state: __mbstate_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _G_fpos64_t"][::std::mem::size_of::<_G_fpos64_t>() - 16usize];
    ["Alignment of _G_fpos64_t"][::std::mem::align_of::<_G_fpos64_t>() - 8usize];
    ["Offset of field: _G_fpos64_t::__pos"][::std::mem::offset_of!(_G_fpos64_t, __pos) - 0usize];
    ["Offset of field: _G_fpos64_t::__state"]
        [::std::mem::offset_of!(_G_fpos64_t, __state) - 8usize];
};
type __fpos64_t = _G_fpos64_t;
type __FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct _IO_wide_data {
    _unused: [u8; 0],
}
type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct _IO_FILE {
    _flags: ::std::os::raw::c_int,
    _IO_read_ptr: *mut ::std::os::raw::c_char,
    _IO_read_end: *mut ::std::os::raw::c_char,
    _IO_read_base: *mut ::std::os::raw::c_char,
    _IO_write_base: *mut ::std::os::raw::c_char,
    _IO_write_ptr: *mut ::std::os::raw::c_char,
    _IO_write_end: *mut ::std::os::raw::c_char,
    _IO_buf_base: *mut ::std::os::raw::c_char,
    _IO_buf_end: *mut ::std::os::raw::c_char,
    _IO_save_base: *mut ::std::os::raw::c_char,
    _IO_backup_base: *mut ::std::os::raw::c_char,
    _IO_save_end: *mut ::std::os::raw::c_char,
    _markers: *mut _IO_marker,
    _chain: *mut _IO_FILE,
    _fileno: ::std::os::raw::c_int,
    _bitfield_align_1: [u32; 0],
    _bitfield_1: __BindgenBitfieldUnit<[u8; 3usize]>,
    _short_backupbuf: [::std::os::raw::c_char; 1usize],
    _old_offset: __off_t,
    _cur_column: ::std::os::raw::c_ushort,
    _vtable_offset: ::std::os::raw::c_schar,
    _shortbuf: [::std::os::raw::c_char; 1usize],
    _lock: *mut _IO_lock_t,
    _offset: __off64_t,
    _codecvt: *mut _IO_codecvt,
    _wide_data: *mut _IO_wide_data,
    _freeres_list: *mut _IO_FILE,
    _freeres_buf: *mut ::std::os::raw::c_void,
    _prevchain: *mut *mut _IO_FILE,
    _mode: ::std::os::raw::c_int,
    _unused3: ::std::os::raw::c_int,
    _total_written: __uint64_t,
    _unused2: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _IO_FILE"][::std::mem::size_of::<_IO_FILE>() - 216usize];
    ["Alignment of _IO_FILE"][::std::mem::align_of::<_IO_FILE>() - 8usize];
    ["Offset of field: _IO_FILE::_flags"][::std::mem::offset_of!(_IO_FILE, _flags) - 0usize];
    ["Offset of field: _IO_FILE::_IO_read_ptr"]
        [::std::mem::offset_of!(_IO_FILE, _IO_read_ptr) - 8usize];
    ["Offset of field: _IO_FILE::_IO_read_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_read_end) - 16usize];
    ["Offset of field: _IO_FILE::_IO_read_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_read_base) - 24usize];
    ["Offset of field: _IO_FILE::_IO_write_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_write_base) - 32usize];
    ["Offset of field: _IO_FILE::_IO_write_ptr"]
        [::std::mem::offset_of!(_IO_FILE, _IO_write_ptr) - 40usize];
    ["Offset of field: _IO_FILE::_IO_write_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_write_end) - 48usize];
    ["Offset of field: _IO_FILE::_IO_buf_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_buf_base) - 56usize];
    ["Offset of field: _IO_FILE::_IO_buf_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_buf_end) - 64usize];
    ["Offset of field: _IO_FILE::_IO_save_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_save_base) - 72usize];
    ["Offset of field: _IO_FILE::_IO_backup_base"]
        [::std::mem::offset_of!(_IO_FILE, _IO_backup_base) - 80usize];
    ["Offset of field: _IO_FILE::_IO_save_end"]
        [::std::mem::offset_of!(_IO_FILE, _IO_save_end) - 88usize];
    ["Offset of field: _IO_FILE::_markers"][::std::mem::offset_of!(_IO_FILE, _markers) - 96usize];
    ["Offset of field: _IO_FILE::_chain"][::std::mem::offset_of!(_IO_FILE, _chain) - 104usize];
    ["Offset of field: _IO_FILE::_fileno"][::std::mem::offset_of!(_IO_FILE, _fileno) - 112usize];
    ["Offset of field: _IO_FILE::_short_backupbuf"]
        [::std::mem::offset_of!(_IO_FILE, _short_backupbuf) - 119usize];
    ["Offset of field: _IO_FILE::_old_offset"]
        [::std::mem::offset_of!(_IO_FILE, _old_offset) - 120usize];
    ["Offset of field: _IO_FILE::_cur_column"]
        [::std::mem::offset_of!(_IO_FILE, _cur_column) - 128usize];
    ["Offset of field: _IO_FILE::_vtable_offset"]
        [::std::mem::offset_of!(_IO_FILE, _vtable_offset) - 130usize];
    ["Offset of field: _IO_FILE::_shortbuf"]
        [::std::mem::offset_of!(_IO_FILE, _shortbuf) - 131usize];
    ["Offset of field: _IO_FILE::_lock"][::std::mem::offset_of!(_IO_FILE, _lock) - 136usize];
    ["Offset of field: _IO_FILE::_offset"][::std::mem::offset_of!(_IO_FILE, _offset) - 144usize];
    ["Offset of field: _IO_FILE::_codecvt"][::std::mem::offset_of!(_IO_FILE, _codecvt) - 152usize];
    ["Offset of field: _IO_FILE::_wide_data"]
        [::std::mem::offset_of!(_IO_FILE, _wide_data) - 160usize];
    ["Offset of field: _IO_FILE::_freeres_list"]
        [::std::mem::offset_of!(_IO_FILE, _freeres_list) - 168usize];
    ["Offset of field: _IO_FILE::_freeres_buf"]
        [::std::mem::offset_of!(_IO_FILE, _freeres_buf) - 176usize];
    ["Offset of field: _IO_FILE::_prevchain"]
        [::std::mem::offset_of!(_IO_FILE, _prevchain) - 184usize];
    ["Offset of field: _IO_FILE::_mode"][::std::mem::offset_of!(_IO_FILE, _mode) - 192usize];
    ["Offset of field: _IO_FILE::_unused3"][::std::mem::offset_of!(_IO_FILE, _unused3) - 196usize];
    ["Offset of field: _IO_FILE::_total_written"]
        [::std::mem::offset_of!(_IO_FILE, _total_written) - 200usize];
    ["Offset of field: _IO_FILE::_unused2"][::std::mem::offset_of!(_IO_FILE, _unused2) - 208usize];
};
type cookie_read_function_t = ::std::option::Option<
    unsafe extern "C" fn(
        __cookie: *mut ::std::os::raw::c_void,
        __buf: *mut ::std::os::raw::c_char,
        __nbytes: usize,
    ) -> __ssize_t,
>;
type cookie_write_function_t = ::std::option::Option<
    unsafe extern "C" fn(
        __cookie: *mut ::std::os::raw::c_void,
        __buf: *const ::std::os::raw::c_char,
        __nbytes: usize,
    ) -> __ssize_t,
>;
type cookie_seek_function_t = ::std::option::Option<
    unsafe extern "C" fn(
        __cookie: *mut ::std::os::raw::c_void,
        __pos: *mut __off64_t,
        __w: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
type cookie_close_function_t = ::std::option::Option<
    unsafe extern "C" fn(__cookie: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct _IO_cookie_io_functions_t {
    read: cookie_read_function_t,
    write: cookie_write_function_t,
    seek: cookie_seek_function_t,
    close: cookie_close_function_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _IO_cookie_io_functions_t"]
        [::std::mem::size_of::<_IO_cookie_io_functions_t>() - 32usize];
    ["Alignment of _IO_cookie_io_functions_t"]
        [::std::mem::align_of::<_IO_cookie_io_functions_t>() - 8usize];
    ["Offset of field: _IO_cookie_io_functions_t::read"]
        [::std::mem::offset_of!(_IO_cookie_io_functions_t, read) - 0usize];
    ["Offset of field: _IO_cookie_io_functions_t::write"]
        [::std::mem::offset_of!(_IO_cookie_io_functions_t, write) - 8usize];
    ["Offset of field: _IO_cookie_io_functions_t::seek"]
        [::std::mem::offset_of!(_IO_cookie_io_functions_t, seek) - 16usize];
    ["Offset of field: _IO_cookie_io_functions_t::close"]
        [::std::mem::offset_of!(_IO_cookie_io_functions_t, close) - 24usize];
};
type __cfloat128 = __BindgenComplex<u128>;
type _Float128 = u128;
type _Float32 = f32;
type _Float64 = f64;
type _Float32x = f64;
type _Float64x = u128;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct div_t {
    quot: ::std::os::raw::c_int,
    rem: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of div_t"][::std::mem::size_of::<div_t>() - 8usize];
    ["Alignment of div_t"][::std::mem::align_of::<div_t>() - 4usize];
    ["Offset of field: div_t::quot"][::std::mem::offset_of!(div_t, quot) - 0usize];
    ["Offset of field: div_t::rem"][::std::mem::offset_of!(div_t, rem) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct ldiv_t {
    quot: ::std::os::raw::c_long,
    rem: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ldiv_t"][::std::mem::size_of::<ldiv_t>() - 16usize];
    ["Alignment of ldiv_t"][::std::mem::align_of::<ldiv_t>() - 8usize];
    ["Offset of field: ldiv_t::quot"][::std::mem::offset_of!(ldiv_t, quot) - 0usize];
    ["Offset of field: ldiv_t::rem"][::std::mem::offset_of!(ldiv_t, rem) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct lldiv_t {
    quot: ::std::os::raw::c_longlong,
    rem: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of lldiv_t"][::std::mem::size_of::<lldiv_t>() - 16usize];
    ["Alignment of lldiv_t"][::std::mem::align_of::<lldiv_t>() - 8usize];
    ["Offset of field: lldiv_t::quot"][::std::mem::offset_of!(lldiv_t, quot) - 0usize];
    ["Offset of field: lldiv_t::rem"][::std::mem::offset_of!(lldiv_t, rem) - 8usize];
};
unsafe extern "C" {
    fn __ctype_get_mb_cur_max() -> usize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct random_data {
    fptr: *mut i32,
    rptr: *mut i32,
    state: *mut i32,
    rand_type: ::std::os::raw::c_int,
    rand_deg: ::std::os::raw::c_int,
    rand_sep: ::std::os::raw::c_int,
    end_ptr: *mut i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of random_data"][::std::mem::size_of::<random_data>() - 48usize];
    ["Alignment of random_data"][::std::mem::align_of::<random_data>() - 8usize];
    ["Offset of field: random_data::fptr"][::std::mem::offset_of!(random_data, fptr) - 0usize];
    ["Offset of field: random_data::rptr"][::std::mem::offset_of!(random_data, rptr) - 8usize];
    ["Offset of field: random_data::state"][::std::mem::offset_of!(random_data, state) - 16usize];
    ["Offset of field: random_data::rand_type"]
        [::std::mem::offset_of!(random_data, rand_type) - 24usize];
    ["Offset of field: random_data::rand_deg"]
        [::std::mem::offset_of!(random_data, rand_deg) - 28usize];
    ["Offset of field: random_data::rand_sep"]
        [::std::mem::offset_of!(random_data, rand_sep) - 32usize];
    ["Offset of field: random_data::end_ptr"]
        [::std::mem::offset_of!(random_data, end_ptr) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct drand48_data {
    __x: [::std::os::raw::c_ushort; 3usize],
    __old_x: [::std::os::raw::c_ushort; 3usize],
    __c: ::std::os::raw::c_ushort,
    __init: ::std::os::raw::c_ushort,
    __a: ::std::os::raw::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drand48_data"][::std::mem::size_of::<drand48_data>() - 24usize];
    ["Alignment of drand48_data"][::std::mem::align_of::<drand48_data>() - 8usize];
    ["Offset of field: drand48_data::__x"][::std::mem::offset_of!(drand48_data, __x) - 0usize];
    ["Offset of field: drand48_data::__old_x"]
        [::std::mem::offset_of!(drand48_data, __old_x) - 6usize];
    ["Offset of field: drand48_data::__c"][::std::mem::offset_of!(drand48_data, __c) - 12usize];
    ["Offset of field: drand48_data::__init"]
        [::std::mem::offset_of!(drand48_data, __init) - 14usize];
    ["Offset of field: drand48_data::__a"][::std::mem::offset_of!(drand48_data, __a) - 16usize];
};
unsafe extern "C" {
    fn _Exit(__status: ::std::os::raw::c_int) -> !;
}
type __compar_fn_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const ::std::os::raw::c_void,
        arg2: *const ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    fn _exit(__status: ::std::os::raw::c_int) -> !;
}
const _PC_LINK_MAX: _bindgen_ty_1 = 0;
const _PC_MAX_CANON: _bindgen_ty_1 = 1;
const _PC_MAX_INPUT: _bindgen_ty_1 = 2;
const _PC_NAME_MAX: _bindgen_ty_1 = 3;
const _PC_PATH_MAX: _bindgen_ty_1 = 4;
const _PC_PIPE_BUF: _bindgen_ty_1 = 5;
const _PC_CHOWN_RESTRICTED: _bindgen_ty_1 = 6;
const _PC_NO_TRUNC: _bindgen_ty_1 = 7;
const _PC_VDISABLE: _bindgen_ty_1 = 8;
const _PC_SYNC_IO: _bindgen_ty_1 = 9;
const _PC_ASYNC_IO: _bindgen_ty_1 = 10;
const _PC_PRIO_IO: _bindgen_ty_1 = 11;
const _PC_SOCK_MAXBUF: _bindgen_ty_1 = 12;
const _PC_FILESIZEBITS: _bindgen_ty_1 = 13;
const _PC_REC_INCR_XFER_SIZE: _bindgen_ty_1 = 14;
const _PC_REC_MAX_XFER_SIZE: _bindgen_ty_1 = 15;
const _PC_REC_MIN_XFER_SIZE: _bindgen_ty_1 = 16;
const _PC_REC_XFER_ALIGN: _bindgen_ty_1 = 17;
const _PC_ALLOC_SIZE_MIN: _bindgen_ty_1 = 18;
const _PC_SYMLINK_MAX: _bindgen_ty_1 = 19;
const _PC_2_SYMLINKS: _bindgen_ty_1 = 20;
type _bindgen_ty_1 = ::std::os::raw::c_uint;
const _SC_ARG_MAX: _bindgen_ty_2 = 0;
const _SC_CHILD_MAX: _bindgen_ty_2 = 1;
const _SC_CLK_TCK: _bindgen_ty_2 = 2;
const _SC_NGROUPS_MAX: _bindgen_ty_2 = 3;
const _SC_OPEN_MAX: _bindgen_ty_2 = 4;
const _SC_STREAM_MAX: _bindgen_ty_2 = 5;
const _SC_TZNAME_MAX: _bindgen_ty_2 = 6;
const _SC_JOB_CONTROL: _bindgen_ty_2 = 7;
const _SC_SAVED_IDS: _bindgen_ty_2 = 8;
const _SC_REALTIME_SIGNALS: _bindgen_ty_2 = 9;
const _SC_PRIORITY_SCHEDULING: _bindgen_ty_2 = 10;
const _SC_TIMERS: _bindgen_ty_2 = 11;
const _SC_ASYNCHRONOUS_IO: _bindgen_ty_2 = 12;
const _SC_PRIORITIZED_IO: _bindgen_ty_2 = 13;
const _SC_SYNCHRONIZED_IO: _bindgen_ty_2 = 14;
const _SC_FSYNC: _bindgen_ty_2 = 15;
const _SC_MAPPED_FILES: _bindgen_ty_2 = 16;
const _SC_MEMLOCK: _bindgen_ty_2 = 17;
const _SC_MEMLOCK_RANGE: _bindgen_ty_2 = 18;
const _SC_MEMORY_PROTECTION: _bindgen_ty_2 = 19;
const _SC_MESSAGE_PASSING: _bindgen_ty_2 = 20;
const _SC_SEMAPHORES: _bindgen_ty_2 = 21;
const _SC_SHARED_MEMORY_OBJECTS: _bindgen_ty_2 = 22;
const _SC_AIO_LISTIO_MAX: _bindgen_ty_2 = 23;
const _SC_AIO_MAX: _bindgen_ty_2 = 24;
const _SC_AIO_PRIO_DELTA_MAX: _bindgen_ty_2 = 25;
const _SC_DELAYTIMER_MAX: _bindgen_ty_2 = 26;
const _SC_MQ_OPEN_MAX: _bindgen_ty_2 = 27;
const _SC_MQ_PRIO_MAX: _bindgen_ty_2 = 28;
const _SC_VERSION: _bindgen_ty_2 = 29;
const _SC_PAGESIZE: _bindgen_ty_2 = 30;
const _SC_RTSIG_MAX: _bindgen_ty_2 = 31;
const _SC_SEM_NSEMS_MAX: _bindgen_ty_2 = 32;
const _SC_SEM_VALUE_MAX: _bindgen_ty_2 = 33;
const _SC_SIGQUEUE_MAX: _bindgen_ty_2 = 34;
const _SC_TIMER_MAX: _bindgen_ty_2 = 35;
const _SC_BC_BASE_MAX: _bindgen_ty_2 = 36;
const _SC_BC_DIM_MAX: _bindgen_ty_2 = 37;
const _SC_BC_SCALE_MAX: _bindgen_ty_2 = 38;
const _SC_BC_STRING_MAX: _bindgen_ty_2 = 39;
const _SC_COLL_WEIGHTS_MAX: _bindgen_ty_2 = 40;
const _SC_EQUIV_CLASS_MAX: _bindgen_ty_2 = 41;
const _SC_EXPR_NEST_MAX: _bindgen_ty_2 = 42;
const _SC_LINE_MAX: _bindgen_ty_2 = 43;
const _SC_RE_DUP_MAX: _bindgen_ty_2 = 44;
const _SC_CHARCLASS_NAME_MAX: _bindgen_ty_2 = 45;
const _SC_2_VERSION: _bindgen_ty_2 = 46;
const _SC_2_C_BIND: _bindgen_ty_2 = 47;
const _SC_2_C_DEV: _bindgen_ty_2 = 48;
const _SC_2_FORT_DEV: _bindgen_ty_2 = 49;
const _SC_2_FORT_RUN: _bindgen_ty_2 = 50;
const _SC_2_SW_DEV: _bindgen_ty_2 = 51;
const _SC_2_LOCALEDEF: _bindgen_ty_2 = 52;
const _SC_PII: _bindgen_ty_2 = 53;
const _SC_PII_XTI: _bindgen_ty_2 = 54;
const _SC_PII_SOCKET: _bindgen_ty_2 = 55;
const _SC_PII_INTERNET: _bindgen_ty_2 = 56;
const _SC_PII_OSI: _bindgen_ty_2 = 57;
const _SC_POLL: _bindgen_ty_2 = 58;
const _SC_SELECT: _bindgen_ty_2 = 59;
const _SC_UIO_MAXIOV: _bindgen_ty_2 = 60;
const _SC_IOV_MAX: _bindgen_ty_2 = 60;
const _SC_PII_INTERNET_STREAM: _bindgen_ty_2 = 61;
const _SC_PII_INTERNET_DGRAM: _bindgen_ty_2 = 62;
const _SC_PII_OSI_COTS: _bindgen_ty_2 = 63;
const _SC_PII_OSI_CLTS: _bindgen_ty_2 = 64;
const _SC_PII_OSI_M: _bindgen_ty_2 = 65;
const _SC_T_IOV_MAX: _bindgen_ty_2 = 66;
const _SC_THREADS: _bindgen_ty_2 = 67;
const _SC_THREAD_SAFE_FUNCTIONS: _bindgen_ty_2 = 68;
const _SC_GETGR_R_SIZE_MAX: _bindgen_ty_2 = 69;
const _SC_GETPW_R_SIZE_MAX: _bindgen_ty_2 = 70;
const _SC_LOGIN_NAME_MAX: _bindgen_ty_2 = 71;
const _SC_TTY_NAME_MAX: _bindgen_ty_2 = 72;
const _SC_THREAD_DESTRUCTOR_ITERATIONS: _bindgen_ty_2 = 73;
const _SC_THREAD_KEYS_MAX: _bindgen_ty_2 = 74;
const _SC_THREAD_STACK_MIN: _bindgen_ty_2 = 75;
const _SC_THREAD_THREADS_MAX: _bindgen_ty_2 = 76;
const _SC_THREAD_ATTR_STACKADDR: _bindgen_ty_2 = 77;
const _SC_THREAD_ATTR_STACKSIZE: _bindgen_ty_2 = 78;
const _SC_THREAD_PRIORITY_SCHEDULING: _bindgen_ty_2 = 79;
const _SC_THREAD_PRIO_INHERIT: _bindgen_ty_2 = 80;
const _SC_THREAD_PRIO_PROTECT: _bindgen_ty_2 = 81;
const _SC_THREAD_PROCESS_SHARED: _bindgen_ty_2 = 82;
const _SC_NPROCESSORS_CONF: _bindgen_ty_2 = 83;
const _SC_NPROCESSORS_ONLN: _bindgen_ty_2 = 84;
const _SC_PHYS_PAGES: _bindgen_ty_2 = 85;
const _SC_AVPHYS_PAGES: _bindgen_ty_2 = 86;
const _SC_ATEXIT_MAX: _bindgen_ty_2 = 87;
const _SC_PASS_MAX: _bindgen_ty_2 = 88;
const _SC_XOPEN_VERSION: _bindgen_ty_2 = 89;
const _SC_XOPEN_XCU_VERSION: _bindgen_ty_2 = 90;
const _SC_XOPEN_UNIX: _bindgen_ty_2 = 91;
const _SC_XOPEN_CRYPT: _bindgen_ty_2 = 92;
const _SC_XOPEN_ENH_I18N: _bindgen_ty_2 = 93;
const _SC_XOPEN_SHM: _bindgen_ty_2 = 94;
const _SC_2_CHAR_TERM: _bindgen_ty_2 = 95;
const _SC_2_C_VERSION: _bindgen_ty_2 = 96;
const _SC_2_UPE: _bindgen_ty_2 = 97;
const _SC_XOPEN_XPG2: _bindgen_ty_2 = 98;
const _SC_XOPEN_XPG3: _bindgen_ty_2 = 99;
const _SC_XOPEN_XPG4: _bindgen_ty_2 = 100;
const _SC_CHAR_BIT: _bindgen_ty_2 = 101;
const _SC_CHAR_MAX: _bindgen_ty_2 = 102;
const _SC_CHAR_MIN: _bindgen_ty_2 = 103;
const _SC_INT_MAX: _bindgen_ty_2 = 104;
const _SC_INT_MIN: _bindgen_ty_2 = 105;
const _SC_LONG_BIT: _bindgen_ty_2 = 106;
const _SC_WORD_BIT: _bindgen_ty_2 = 107;
const _SC_MB_LEN_MAX: _bindgen_ty_2 = 108;
const _SC_NZERO: _bindgen_ty_2 = 109;
const _SC_SSIZE_MAX: _bindgen_ty_2 = 110;
const _SC_SCHAR_MAX: _bindgen_ty_2 = 111;
const _SC_SCHAR_MIN: _bindgen_ty_2 = 112;
const _SC_SHRT_MAX: _bindgen_ty_2 = 113;
const _SC_SHRT_MIN: _bindgen_ty_2 = 114;
const _SC_UCHAR_MAX: _bindgen_ty_2 = 115;
const _SC_UINT_MAX: _bindgen_ty_2 = 116;
const _SC_ULONG_MAX: _bindgen_ty_2 = 117;
const _SC_USHRT_MAX: _bindgen_ty_2 = 118;
const _SC_NL_ARGMAX: _bindgen_ty_2 = 119;
const _SC_NL_LANGMAX: _bindgen_ty_2 = 120;
const _SC_NL_MSGMAX: _bindgen_ty_2 = 121;
const _SC_NL_NMAX: _bindgen_ty_2 = 122;
const _SC_NL_SETMAX: _bindgen_ty_2 = 123;
const _SC_NL_TEXTMAX: _bindgen_ty_2 = 124;
const _SC_XBS5_ILP32_OFF32: _bindgen_ty_2 = 125;
const _SC_XBS5_ILP32_OFFBIG: _bindgen_ty_2 = 126;
const _SC_XBS5_LP64_OFF64: _bindgen_ty_2 = 127;
const _SC_XBS5_LPBIG_OFFBIG: _bindgen_ty_2 = 128;
const _SC_XOPEN_LEGACY: _bindgen_ty_2 = 129;
const _SC_XOPEN_REALTIME: _bindgen_ty_2 = 130;
const _SC_XOPEN_REALTIME_THREADS: _bindgen_ty_2 = 131;
const _SC_ADVISORY_INFO: _bindgen_ty_2 = 132;
const _SC_BARRIERS: _bindgen_ty_2 = 133;
const _SC_BASE: _bindgen_ty_2 = 134;
const _SC_C_LANG_SUPPORT: _bindgen_ty_2 = 135;
const _SC_C_LANG_SUPPORT_R: _bindgen_ty_2 = 136;
const _SC_CLOCK_SELECTION: _bindgen_ty_2 = 137;
const _SC_CPUTIME: _bindgen_ty_2 = 138;
const _SC_THREAD_CPUTIME: _bindgen_ty_2 = 139;
const _SC_DEVICE_IO: _bindgen_ty_2 = 140;
const _SC_DEVICE_SPECIFIC: _bindgen_ty_2 = 141;
const _SC_DEVICE_SPECIFIC_R: _bindgen_ty_2 = 142;
const _SC_FD_MGMT: _bindgen_ty_2 = 143;
const _SC_FIFO: _bindgen_ty_2 = 144;
const _SC_PIPE: _bindgen_ty_2 = 145;
const _SC_FILE_ATTRIBUTES: _bindgen_ty_2 = 146;
const _SC_FILE_LOCKING: _bindgen_ty_2 = 147;
const _SC_FILE_SYSTEM: _bindgen_ty_2 = 148;
const _SC_MONOTONIC_CLOCK: _bindgen_ty_2 = 149;
const _SC_MULTI_PROCESS: _bindgen_ty_2 = 150;
const _SC_SINGLE_PROCESS: _bindgen_ty_2 = 151;
const _SC_NETWORKING: _bindgen_ty_2 = 152;
const _SC_READER_WRITER_LOCKS: _bindgen_ty_2 = 153;
const _SC_SPIN_LOCKS: _bindgen_ty_2 = 154;
const _SC_REGEXP: _bindgen_ty_2 = 155;
const _SC_REGEX_VERSION: _bindgen_ty_2 = 156;
const _SC_SHELL: _bindgen_ty_2 = 157;
const _SC_SIGNALS: _bindgen_ty_2 = 158;
const _SC_SPAWN: _bindgen_ty_2 = 159;
const _SC_SPORADIC_SERVER: _bindgen_ty_2 = 160;
const _SC_THREAD_SPORADIC_SERVER: _bindgen_ty_2 = 161;
const _SC_SYSTEM_DATABASE: _bindgen_ty_2 = 162;
const _SC_SYSTEM_DATABASE_R: _bindgen_ty_2 = 163;
const _SC_TIMEOUTS: _bindgen_ty_2 = 164;
const _SC_TYPED_MEMORY_OBJECTS: _bindgen_ty_2 = 165;
const _SC_USER_GROUPS: _bindgen_ty_2 = 166;
const _SC_USER_GROUPS_R: _bindgen_ty_2 = 167;
const _SC_2_PBS: _bindgen_ty_2 = 168;
const _SC_2_PBS_ACCOUNTING: _bindgen_ty_2 = 169;
const _SC_2_PBS_LOCATE: _bindgen_ty_2 = 170;
const _SC_2_PBS_MESSAGE: _bindgen_ty_2 = 171;
const _SC_2_PBS_TRACK: _bindgen_ty_2 = 172;
const _SC_SYMLOOP_MAX: _bindgen_ty_2 = 173;
const _SC_STREAMS: _bindgen_ty_2 = 174;
const _SC_2_PBS_CHECKPOINT: _bindgen_ty_2 = 175;
const _SC_V6_ILP32_OFF32: _bindgen_ty_2 = 176;
const _SC_V6_ILP32_OFFBIG: _bindgen_ty_2 = 177;
const _SC_V6_LP64_OFF64: _bindgen_ty_2 = 178;
const _SC_V6_LPBIG_OFFBIG: _bindgen_ty_2 = 179;
const _SC_HOST_NAME_MAX: _bindgen_ty_2 = 180;
const _SC_TRACE: _bindgen_ty_2 = 181;
const _SC_TRACE_EVENT_FILTER: _bindgen_ty_2 = 182;
const _SC_TRACE_INHERIT: _bindgen_ty_2 = 183;
const _SC_TRACE_LOG: _bindgen_ty_2 = 184;
const _SC_LEVEL1_ICACHE_SIZE: _bindgen_ty_2 = 185;
const _SC_LEVEL1_ICACHE_ASSOC: _bindgen_ty_2 = 186;
const _SC_LEVEL1_ICACHE_LINESIZE: _bindgen_ty_2 = 187;
const _SC_LEVEL1_DCACHE_SIZE: _bindgen_ty_2 = 188;
const _SC_LEVEL1_DCACHE_ASSOC: _bindgen_ty_2 = 189;
const _SC_LEVEL1_DCACHE_LINESIZE: _bindgen_ty_2 = 190;
const _SC_LEVEL2_CACHE_SIZE: _bindgen_ty_2 = 191;
const _SC_LEVEL2_CACHE_ASSOC: _bindgen_ty_2 = 192;
const _SC_LEVEL2_CACHE_LINESIZE: _bindgen_ty_2 = 193;
const _SC_LEVEL3_CACHE_SIZE: _bindgen_ty_2 = 194;
const _SC_LEVEL3_CACHE_ASSOC: _bindgen_ty_2 = 195;
const _SC_LEVEL3_CACHE_LINESIZE: _bindgen_ty_2 = 196;
const _SC_LEVEL4_CACHE_SIZE: _bindgen_ty_2 = 197;
const _SC_LEVEL4_CACHE_ASSOC: _bindgen_ty_2 = 198;
const _SC_LEVEL4_CACHE_LINESIZE: _bindgen_ty_2 = 199;
const _SC_IPV6: _bindgen_ty_2 = 235;
const _SC_RAW_SOCKETS: _bindgen_ty_2 = 236;
const _SC_V7_ILP32_OFF32: _bindgen_ty_2 = 237;
const _SC_V7_ILP32_OFFBIG: _bindgen_ty_2 = 238;
const _SC_V7_LP64_OFF64: _bindgen_ty_2 = 239;
const _SC_V7_LPBIG_OFFBIG: _bindgen_ty_2 = 240;
const _SC_SS_REPL_MAX: _bindgen_ty_2 = 241;
const _SC_TRACE_EVENT_NAME_MAX: _bindgen_ty_2 = 242;
const _SC_TRACE_NAME_MAX: _bindgen_ty_2 = 243;
const _SC_TRACE_SYS_MAX: _bindgen_ty_2 = 244;
const _SC_TRACE_USER_EVENT_MAX: _bindgen_ty_2 = 245;
const _SC_XOPEN_STREAMS: _bindgen_ty_2 = 246;
const _SC_THREAD_ROBUST_PRIO_INHERIT: _bindgen_ty_2 = 247;
const _SC_THREAD_ROBUST_PRIO_PROTECT: _bindgen_ty_2 = 248;
const _SC_MINSIGSTKSZ: _bindgen_ty_2 = 249;
const _SC_SIGSTKSZ: _bindgen_ty_2 = 250;
type _bindgen_ty_2 = ::std::os::raw::c_uint;
const _CS_PATH: _bindgen_ty_3 = 0;
const _CS_V6_WIDTH_RESTRICTED_ENVS: _bindgen_ty_3 = 1;
const _CS_GNU_LIBC_VERSION: _bindgen_ty_3 = 2;
const _CS_GNU_LIBPTHREAD_VERSION: _bindgen_ty_3 = 3;
const _CS_V5_WIDTH_RESTRICTED_ENVS: _bindgen_ty_3 = 4;
const _CS_V7_WIDTH_RESTRICTED_ENVS: _bindgen_ty_3 = 5;
const _CS_LFS_CFLAGS: _bindgen_ty_3 = 1000;
const _CS_LFS_LDFLAGS: _bindgen_ty_3 = 1001;
const _CS_LFS_LIBS: _bindgen_ty_3 = 1002;
const _CS_LFS_LINTFLAGS: _bindgen_ty_3 = 1003;
const _CS_LFS64_CFLAGS: _bindgen_ty_3 = 1004;
const _CS_LFS64_LDFLAGS: _bindgen_ty_3 = 1005;
const _CS_LFS64_LIBS: _bindgen_ty_3 = 1006;
const _CS_LFS64_LINTFLAGS: _bindgen_ty_3 = 1007;
const _CS_XBS5_ILP32_OFF32_CFLAGS: _bindgen_ty_3 = 1100;
const _CS_XBS5_ILP32_OFF32_LDFLAGS: _bindgen_ty_3 = 1101;
const _CS_XBS5_ILP32_OFF32_LIBS: _bindgen_ty_3 = 1102;
const _CS_XBS5_ILP32_OFF32_LINTFLAGS: _bindgen_ty_3 = 1103;
const _CS_XBS5_ILP32_OFFBIG_CFLAGS: _bindgen_ty_3 = 1104;
const _CS_XBS5_ILP32_OFFBIG_LDFLAGS: _bindgen_ty_3 = 1105;
const _CS_XBS5_ILP32_OFFBIG_LIBS: _bindgen_ty_3 = 1106;
const _CS_XBS5_ILP32_OFFBIG_LINTFLAGS: _bindgen_ty_3 = 1107;
const _CS_XBS5_LP64_OFF64_CFLAGS: _bindgen_ty_3 = 1108;
const _CS_XBS5_LP64_OFF64_LDFLAGS: _bindgen_ty_3 = 1109;
const _CS_XBS5_LP64_OFF64_LIBS: _bindgen_ty_3 = 1110;
const _CS_XBS5_LP64_OFF64_LINTFLAGS: _bindgen_ty_3 = 1111;
const _CS_XBS5_LPBIG_OFFBIG_CFLAGS: _bindgen_ty_3 = 1112;
const _CS_XBS5_LPBIG_OFFBIG_LDFLAGS: _bindgen_ty_3 = 1113;
const _CS_XBS5_LPBIG_OFFBIG_LIBS: _bindgen_ty_3 = 1114;
const _CS_XBS5_LPBIG_OFFBIG_LINTFLAGS: _bindgen_ty_3 = 1115;
const _CS_POSIX_V6_ILP32_OFF32_CFLAGS: _bindgen_ty_3 = 1116;
const _CS_POSIX_V6_ILP32_OFF32_LDFLAGS: _bindgen_ty_3 = 1117;
const _CS_POSIX_V6_ILP32_OFF32_LIBS: _bindgen_ty_3 = 1118;
const _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS: _bindgen_ty_3 = 1119;
const _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS: _bindgen_ty_3 = 1120;
const _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS: _bindgen_ty_3 = 1121;
const _CS_POSIX_V6_ILP32_OFFBIG_LIBS: _bindgen_ty_3 = 1122;
const _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS: _bindgen_ty_3 = 1123;
const _CS_POSIX_V6_LP64_OFF64_CFLAGS: _bindgen_ty_3 = 1124;
const _CS_POSIX_V6_LP64_OFF64_LDFLAGS: _bindgen_ty_3 = 1125;
const _CS_POSIX_V6_LP64_OFF64_LIBS: _bindgen_ty_3 = 1126;
const _CS_POSIX_V6_LP64_OFF64_LINTFLAGS: _bindgen_ty_3 = 1127;
const _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS: _bindgen_ty_3 = 1128;
const _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS: _bindgen_ty_3 = 1129;
const _CS_POSIX_V6_LPBIG_OFFBIG_LIBS: _bindgen_ty_3 = 1130;
const _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS: _bindgen_ty_3 = 1131;
const _CS_POSIX_V7_ILP32_OFF32_CFLAGS: _bindgen_ty_3 = 1132;
const _CS_POSIX_V7_ILP32_OFF32_LDFLAGS: _bindgen_ty_3 = 1133;
const _CS_POSIX_V7_ILP32_OFF32_LIBS: _bindgen_ty_3 = 1134;
const _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS: _bindgen_ty_3 = 1135;
const _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS: _bindgen_ty_3 = 1136;
const _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS: _bindgen_ty_3 = 1137;
const _CS_POSIX_V7_ILP32_OFFBIG_LIBS: _bindgen_ty_3 = 1138;
const _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS: _bindgen_ty_3 = 1139;
const _CS_POSIX_V7_LP64_OFF64_CFLAGS: _bindgen_ty_3 = 1140;
const _CS_POSIX_V7_LP64_OFF64_LDFLAGS: _bindgen_ty_3 = 1141;
const _CS_POSIX_V7_LP64_OFF64_LIBS: _bindgen_ty_3 = 1142;
const _CS_POSIX_V7_LP64_OFF64_LINTFLAGS: _bindgen_ty_3 = 1143;
const _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS: _bindgen_ty_3 = 1144;
const _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS: _bindgen_ty_3 = 1145;
const _CS_POSIX_V7_LPBIG_OFFBIG_LIBS: _bindgen_ty_3 = 1146;
const _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS: _bindgen_ty_3 = 1147;
const _CS_V6_ENV: _bindgen_ty_3 = 1148;
const _CS_V7_ENV: _bindgen_ty_3 = 1149;
type _bindgen_ty_3 = ::std::os::raw::c_uint;
unsafe extern "C" {
    fn __getpgid(__pid: __pid_t) -> __pid_t;
}
#[repr(C)]
#[derive(Debug, Clone)]
struct tm {
    tm_sec: ::std::os::raw::c_int,
    tm_min: ::std::os::raw::c_int,
    tm_hour: ::std::os::raw::c_int,
    tm_mday: ::std::os::raw::c_int,
    tm_mon: ::std::os::raw::c_int,
    tm_year: ::std::os::raw::c_int,
    tm_wday: ::std::os::raw::c_int,
    tm_yday: ::std::os::raw::c_int,
    tm_isdst: ::std::os::raw::c_int,
    tm_gmtoff: ::std::os::raw::c_long,
    tm_zone: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tm"][::std::mem::size_of::<tm>() - 56usize];
    ["Alignment of tm"][::std::mem::align_of::<tm>() - 8usize];
    ["Offset of field: tm::tm_sec"][::std::mem::offset_of!(tm, tm_sec) - 0usize];
    ["Offset of field: tm::tm_min"][::std::mem::offset_of!(tm, tm_min) - 4usize];
    ["Offset of field: tm::tm_hour"][::std::mem::offset_of!(tm, tm_hour) - 8usize];
    ["Offset of field: tm::tm_mday"][::std::mem::offset_of!(tm, tm_mday) - 12usize];
    ["Offset of field: tm::tm_mon"][::std::mem::offset_of!(tm, tm_mon) - 16usize];
    ["Offset of field: tm::tm_year"][::std::mem::offset_of!(tm, tm_year) - 20usize];
    ["Offset of field: tm::tm_wday"][::std::mem::offset_of!(tm, tm_wday) - 24usize];
    ["Offset of field: tm::tm_yday"][::std::mem::offset_of!(tm, tm_yday) - 28usize];
    ["Offset of field: tm::tm_isdst"][::std::mem::offset_of!(tm, tm_isdst) - 32usize];
    ["Offset of field: tm::tm_gmtoff"][::std::mem::offset_of!(tm, tm_gmtoff) - 40usize];
    ["Offset of field: tm::tm_zone"][::std::mem::offset_of!(tm, tm_zone) - 48usize];
};
#[repr(C)]
#[derive(Debug, Clone)]
struct itimerspec {
    it_interval: timespec,
    it_value: timespec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of itimerspec"][::std::mem::size_of::<itimerspec>() - 32usize];
    ["Alignment of itimerspec"][::std::mem::align_of::<itimerspec>() - 8usize];
    ["Offset of field: itimerspec::it_interval"]
        [::std::mem::offset_of!(itimerspec, it_interval) - 0usize];
    ["Offset of field: itimerspec::it_value"]
        [::std::mem::offset_of!(itimerspec, it_value) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __locale_struct {
    __locales: [*mut __locale_data; 13usize],
    __ctype_b: *const ::std::os::raw::c_ushort,
    __ctype_tolower: *const ::std::os::raw::c_int,
    __ctype_toupper: *const ::std::os::raw::c_int,
    __names: [*const ::std::os::raw::c_char; 13usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __locale_struct"][::std::mem::size_of::<__locale_struct>() - 232usize];
    ["Alignment of __locale_struct"][::std::mem::align_of::<__locale_struct>() - 8usize];
    ["Offset of field: __locale_struct::__locales"]
        [::std::mem::offset_of!(__locale_struct, __locales) - 0usize];
    ["Offset of field: __locale_struct::__ctype_b"]
        [::std::mem::offset_of!(__locale_struct, __ctype_b) - 104usize];
    ["Offset of field: __locale_struct::__ctype_tolower"]
        [::std::mem::offset_of!(__locale_struct, __ctype_tolower) - 112usize];
    ["Offset of field: __locale_struct::__ctype_toupper"]
        [::std::mem::offset_of!(__locale_struct, __ctype_toupper) - 120usize];
    ["Offset of field: __locale_struct::__names"]
        [::std::mem::offset_of!(__locale_struct, __names) - 128usize];
};
type __locale_t = *mut __locale_struct;
unsafe extern "C" {
    static mut __tzname: [*mut ::std::os::raw::c_char; 2usize];
}
unsafe extern "C" {
    static mut __daylight: ::std::os::raw::c_int;
}
unsafe extern "C" {
    static mut __timezone: ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn clock_gettime(__clock_id: clockid_t, __tp: *mut timespec) -> ::std::os::raw::c_int;
}
type cudaIpcMemHandle_t = [::std::os::raw::c_char; 64usize];
#[doc = " @brief  Keyword\n The IMAGE_KEYWORD structure includes :\n \t- name\n \t- type\n \t- value"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct IMAGE_KEYWORD {
    #[doc = "< keyword name"]
    name: [::std::os::raw::c_char; 16usize],
    #[doc = "< N: unused, L: long, D: double, S: 16-char string"]
    type_: ::std::os::raw::c_char,
    value: IMAGE_KEYWORD__bindgen_ty_1,
    cnt: u64,
    comment: [::std::os::raw::c_char; 80usize],
}

impl Default for IMAGE_KEYWORD {
    fn default() -> Self {
        Self::new()
    }
}

impl IMAGE_KEYWORD {
    pub fn new() -> Self {
        Self {
            name: [0; 16usize],
            type_: 'N' as i8,
            value: IMAGE_KEYWORD__bindgen_ty_1 { numl: 0 },
            cnt: 0,
            comment: [0; 80usize],
        }
    }
}

#[repr(C)]
#[derive(Copy, Clone)]
union IMAGE_KEYWORD__bindgen_ty_1 {
    numl: i64,
    numf: f64,
    valstr: [::std::os::raw::c_char; 16usize],
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_KEYWORD__bindgen_ty_1"]
        [::std::mem::size_of::<IMAGE_KEYWORD__bindgen_ty_1>() - 16usize];
    ["Alignment of IMAGE_KEYWORD__bindgen_ty_1"]
        [::std::mem::align_of::<IMAGE_KEYWORD__bindgen_ty_1>() - 8usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::numl"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, numl) - 0usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::numf"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, numf) - 0usize];
    ["Offset of field: IMAGE_KEYWORD__bindgen_ty_1::valstr"]
        [::std::mem::offset_of!(IMAGE_KEYWORD__bindgen_ty_1, valstr) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_KEYWORD"][::std::mem::size_of::<IMAGE_KEYWORD>() - 128usize];
    ["Alignment of IMAGE_KEYWORD"][::std::mem::align_of::<IMAGE_KEYWORD>() - 8usize];
    ["Offset of field: IMAGE_KEYWORD::name"][::std::mem::offset_of!(IMAGE_KEYWORD, name) - 0usize];
    ["Offset of field: IMAGE_KEYWORD::type_"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, type_) - 16usize];
    ["Offset of field: IMAGE_KEYWORD::value"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, value) - 24usize];
    ["Offset of field: IMAGE_KEYWORD::cnt"][::std::mem::offset_of!(IMAGE_KEYWORD, cnt) - 40usize];
    ["Offset of field: IMAGE_KEYWORD::comment"]
        [::std::mem::offset_of!(IMAGE_KEYWORD, comment) - 48usize];
};
#[allow(clippy::upper_case_acronyms)]
#[doc = " @brief structure holding two 8-byte integers\n\n Used in an union with struct timespec to ensure fixed 16 byte length"]
#[repr(C)]
#[derive(Debug, Clone)]
struct TIMESPECFIXED {
    firstlong: i64,
    secondlong: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of TIMESPECFIXED"][::std::mem::size_of::<TIMESPECFIXED>() - 16usize];
    ["Alignment of TIMESPECFIXED"][::std::mem::align_of::<TIMESPECFIXED>() - 8usize];
    ["Offset of field: TIMESPECFIXED::firstlong"]
        [::std::mem::offset_of!(TIMESPECFIXED, firstlong) - 0usize];
    ["Offset of field: TIMESPECFIXED::secondlong"]
        [::std::mem::offset_of!(TIMESPECFIXED, secondlong) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct complex_float {
    re: f32,
    im: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of complex_float"][::std::mem::size_of::<complex_float>() - 8usize];
    ["Alignment of complex_float"][::std::mem::align_of::<complex_float>() - 4usize];
    ["Offset of field: complex_float::re"][::std::mem::offset_of!(complex_float, re) - 0usize];
    ["Offset of field: complex_float::im"][::std::mem::offset_of!(complex_float, im) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct complex_double {
    re: f64,
    im: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of complex_double"][::std::mem::size_of::<complex_double>() - 16usize];
    ["Alignment of complex_double"][::std::mem::align_of::<complex_double>() - 8usize];
    ["Offset of field: complex_double::re"][::std::mem::offset_of!(complex_double, re) - 0usize];
    ["Offset of field: complex_double::im"][::std::mem::offset_of!(complex_double, im) - 8usize];
};

///
/// Image metadata
///
#[repr(C)]
#[derive(Debug, Clone, PartialEq)]
pub struct IMAGE_METADATA {
    pub version: [::std::os::raw::c_char; 32usize],
    #[doc = " @brief Image Name"]
    pub name: [::std::os::raw::c_char; 80usize],
    #[doc = " @brief Number of axis\n\n @warning 1, 2 or 3. Values above 3 not supported."]
    pub naxis: u8,
    #[doc = " @brief Image size along each axis\n\n  If naxis = 1 (1D image), size[1] and size[2] are irrelevant"]
    pub size: [u32; 3usize],
    #[doc = " @brief Number of elements in image\n\n This is computed upon image creation"]
    pub nelement: u64,
    #[doc = " @brief Data type\n\n Encoded according to data type defines.\n  -  1: uint8_t\n \t-  2: int8_t\n \t-  3: uint16_t\n \t-  4: int16_t\n \t-  5: uint32_t\n \t-  6: int32_t\n \t-  7: uint64_t\n \t-  8: int64_t\n \t-  9: IEEE 754 single-precision binary floating-point format: binary32\n  - 10: IEEE 754 double-precision binary floating-point format: binary64\n  - 11: complex_float\n  - 12: complex double\n  - 13: half precision floating-point\n"]
    pub datatype: u8,
    #[doc = "< image type"]
    pub imagetype: u64,
    pub creationtime: timespec,
    pub lastaccesstime: timespec,
    pub atime: timespec,
    pub writetime: timespec,
    #[doc = "< PID of process that created the stream (if shared = 1)"]
    pub creatorPID: pid_t,
    #[doc = "< PID of process owning the stream (if shared = 1)"]
    pub ownerPID: pid_t,
    #[doc = "< stream is in shared memory"]
    pub shared: u8,
    #[doc = "< inode nummber if shared memory"]
    pub inode: ino_t,
    #[doc = "< -1 if in CPU memory, >=0 if in GPU memory on `location` device"]
    pub location: i8,
    #[doc = "< 1 to log image (default); 0 : do not log: 2 : stop log (then goes back to 2)"]
    pub status: u8,
    #[doc = "< bitmask, encodes read/write permissions.... NOTE: enum instead of defines"]
    pub flag: u64,
    #[doc = "< set to 1 to start logging"]
    pub logflag: u8,
    #[doc = "< number of semaphores supported, specified at image creation"]
    pub sem: u16,
    #[doc = "< number of streamproctrace entries"]
    pub NBproctrace: u16,
    #[doc = "< counter (incremented if image is updated)"]
    pub cnt0: u64,
    #[doc = "< in 3D rolling buffer image, this is the last slice written"]
    pub cnt1: u64,
    #[doc = "< in cnt2-based syncronization, proceed until cnt0=cnt2"]
    pub cnt2: u64,
    #[doc = "< 1 if image is being written"]
    pub write: u8,
    #[doc = "< number of keywords (max: 65536)"]
    pub NBkw: u16,
    pub CBsize: u32,
    pub CBindex: u32,
    pub CBcycle: u64,
    pub imdatamemsize: u64,
    pub cudaMemHandle: cudaIpcMemHandle_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE_METADATA"][::std::mem::size_of::<IMAGE_METADATA>() - 384usize];
    ["Alignment of IMAGE_METADATA"][::std::mem::align_of::<IMAGE_METADATA>() - 8usize];
    ["Offset of field: IMAGE_METADATA::version"]
        [::std::mem::offset_of!(IMAGE_METADATA, version) - 0usize];
    ["Offset of field: IMAGE_METADATA::name"]
        [::std::mem::offset_of!(IMAGE_METADATA, name) - 32usize];
    ["Offset of field: IMAGE_METADATA::naxis"]
        [::std::mem::offset_of!(IMAGE_METADATA, naxis) - 112usize];
    ["Offset of field: IMAGE_METADATA::size"]
        [::std::mem::offset_of!(IMAGE_METADATA, size) - 116usize];
    ["Offset of field: IMAGE_METADATA::nelement"]
        [::std::mem::offset_of!(IMAGE_METADATA, nelement) - 128usize];
    ["Offset of field: IMAGE_METADATA::datatype"]
        [::std::mem::offset_of!(IMAGE_METADATA, datatype) - 136usize];
    ["Offset of field: IMAGE_METADATA::imagetype"]
        [::std::mem::offset_of!(IMAGE_METADATA, imagetype) - 144usize];
    ["Offset of field: IMAGE_METADATA::creationtime"]
        [::std::mem::offset_of!(IMAGE_METADATA, creationtime) - 152usize];
    ["Offset of field: IMAGE_METADATA::lastaccesstime"]
        [::std::mem::offset_of!(IMAGE_METADATA, lastaccesstime) - 168usize];
    ["Offset of field: IMAGE_METADATA::atime"]
        [::std::mem::offset_of!(IMAGE_METADATA, atime) - 184usize];
    ["Offset of field: IMAGE_METADATA::writetime"]
        [::std::mem::offset_of!(IMAGE_METADATA, writetime) - 200usize];
    ["Offset of field: IMAGE_METADATA::creatorPID"]
        [::std::mem::offset_of!(IMAGE_METADATA, creatorPID) - 216usize];
    ["Offset of field: IMAGE_METADATA::ownerPID"]
        [::std::mem::offset_of!(IMAGE_METADATA, ownerPID) - 220usize];
    ["Offset of field: IMAGE_METADATA::shared"]
        [::std::mem::offset_of!(IMAGE_METADATA, shared) - 224usize];
    ["Offset of field: IMAGE_METADATA::inode"]
        [::std::mem::offset_of!(IMAGE_METADATA, inode) - 232usize];
    ["Offset of field: IMAGE_METADATA::location"]
        [::std::mem::offset_of!(IMAGE_METADATA, location) - 240usize];
    ["Offset of field: IMAGE_METADATA::status"]
        [::std::mem::offset_of!(IMAGE_METADATA, status) - 241usize];
    ["Offset of field: IMAGE_METADATA::flag"]
        [::std::mem::offset_of!(IMAGE_METADATA, flag) - 248usize];
    ["Offset of field: IMAGE_METADATA::logflag"]
        [::std::mem::offset_of!(IMAGE_METADATA, logflag) - 256usize];
    ["Offset of field: IMAGE_METADATA::sem"]
        [::std::mem::offset_of!(IMAGE_METADATA, sem) - 258usize];
    ["Offset of field: IMAGE_METADATA::NBproctrace"]
        [::std::mem::offset_of!(IMAGE_METADATA, NBproctrace) - 260usize];
    ["Offset of field: IMAGE_METADATA::cnt0"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt0) - 264usize];
    ["Offset of field: IMAGE_METADATA::cnt1"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt1) - 272usize];
    ["Offset of field: IMAGE_METADATA::cnt2"]
        [::std::mem::offset_of!(IMAGE_METADATA, cnt2) - 280usize];
    ["Offset of field: IMAGE_METADATA::write"]
        [::std::mem::offset_of!(IMAGE_METADATA, write) - 288usize];
    ["Offset of field: IMAGE_METADATA::NBkw"]
        [::std::mem::offset_of!(IMAGE_METADATA, NBkw) - 290usize];
    ["Offset of field: IMAGE_METADATA::CBsize"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBsize) - 292usize];
    ["Offset of field: IMAGE_METADATA::CBindex"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBindex) - 296usize];
    ["Offset of field: IMAGE_METADATA::CBcycle"]
        [::std::mem::offset_of!(IMAGE_METADATA, CBcycle) - 304usize];
    ["Offset of field: IMAGE_METADATA::imdatamemsize"]
        [::std::mem::offset_of!(IMAGE_METADATA, imdatamemsize) - 312usize];
    ["Offset of field: IMAGE_METADATA::cudaMemHandle"]
        [::std::mem::offset_of!(IMAGE_METADATA, cudaMemHandle) - 320usize];
};
#[doc = " @brief STREAM_PROC_TRACE holds trigger and timing info\n\n Array of STREAM_PROC_TRACE is held within streams to track history.\n This information is assembled by a process, and then written to\n all streams it writes.\n"]
#[repr(C)]
#[derive(Debug, Clone)]
pub struct STREAM_PROC_TRACE {
    triggermode: ::std::os::raw::c_int,
    #[doc = "< PID of process writing stream. 0 if no entry"]
    procwrite_PID: pid_t,
    #[doc = "< trigger stream inode"]
    trigger_inode: ino_t,
    #[doc = "< timestamp process triggered"]
    ts_procstart: timespec,
    #[doc = "< timestamp write this stream"]
    ts_streamupdate: timespec,
    #[doc = "< trigger semaphore"]
    trigsemindex: ::std::os::raw::c_int,
    triggerstatus: ::std::os::raw::c_int,
    #[doc = "< trigger stream cnt0 value at trigger"]
    cnt0: u64,
}

impl Default for STREAM_PROC_TRACE {
    fn default() -> Self {
        Self::new()
    }
}

impl STREAM_PROC_TRACE {
    pub fn new() -> Self {
        Self {
            triggermode: 0, // TODO: This is not explicitly set in the C code
            procwrite_PID: 0,
            trigger_inode: 0,
            ts_procstart: timespec::new(),
            ts_streamupdate: timespec::new(),
            trigsemindex: -1,
            triggerstatus: 0, // TODO: This is not explicitly set in the C code,
            cnt0: 0,
        }
    }
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of STREAM_PROC_TRACE"][::std::mem::size_of::<STREAM_PROC_TRACE>() - 64usize];
    ["Alignment of STREAM_PROC_TRACE"][::std::mem::align_of::<STREAM_PROC_TRACE>() - 8usize];
    ["Offset of field: STREAM_PROC_TRACE::triggermode"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, triggermode) - 0usize];
    ["Offset of field: STREAM_PROC_TRACE::procwrite_PID"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, procwrite_PID) - 4usize];
    ["Offset of field: STREAM_PROC_TRACE::trigger_inode"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, trigger_inode) - 8usize];
    ["Offset of field: STREAM_PROC_TRACE::ts_procstart"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, ts_procstart) - 16usize];
    ["Offset of field: STREAM_PROC_TRACE::ts_streamupdate"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, ts_streamupdate) - 32usize];
    ["Offset of field: STREAM_PROC_TRACE::trigsemindex"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, trigsemindex) - 48usize];
    ["Offset of field: STREAM_PROC_TRACE::triggerstatus"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, triggerstatus) - 52usize];
    ["Offset of field: STREAM_PROC_TRACE::cnt0"]
        [::std::mem::offset_of!(STREAM_PROC_TRACE, cnt0) - 56usize];
};
#[doc = " @brief CBFRAMEMD fast access circular buffer metadata"]
#[repr(C)]
#[derive(Debug, Clone)]
pub struct CBFRAMEMD {
    cnt0: u64,
    cnt1: u64,
    atime: timespec,
    writetime: timespec,
}
impl Default for CBFRAMEMD {
    fn default() -> Self {
        Self::new()
    }
}

impl CBFRAMEMD {
    pub fn new() -> Self {
        Self {
            cnt0: 0,
            cnt1: 0,
            atime: timespec::new(),
            writetime: timespec::new(),
        }
    }
}

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CBFRAMEMD"][::std::mem::size_of::<CBFRAMEMD>() - 48usize];
    ["Alignment of CBFRAMEMD"][::std::mem::align_of::<CBFRAMEMD>() - 8usize];
    ["Offset of field: CBFRAMEMD::cnt0"][::std::mem::offset_of!(CBFRAMEMD, cnt0) - 0usize];
    ["Offset of field: CBFRAMEMD::cnt1"][::std::mem::offset_of!(CBFRAMEMD, cnt1) - 8usize];
    ["Offset of field: CBFRAMEMD::atime"][::std::mem::offset_of!(CBFRAMEMD, atime) - 16usize];
    ["Offset of field: CBFRAMEMD::writetime"]
        [::std::mem::offset_of!(CBFRAMEMD, writetime) - 32usize];
};
#[allow(clippy::upper_case_acronyms)]
#[repr(C)]
#[derive(Debug, Clone)]
struct FRAMEWRITEMD {
    cnt0: u64,
    wpid: pid_t,
    writetime: timespec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FRAMEWRITEMD"][::std::mem::size_of::<FRAMEWRITEMD>() - 32usize];
    ["Alignment of FRAMEWRITEMD"][::std::mem::align_of::<FRAMEWRITEMD>() - 8usize];
    ["Offset of field: FRAMEWRITEMD::cnt0"][::std::mem::offset_of!(FRAMEWRITEMD, cnt0) - 0usize];
    ["Offset of field: FRAMEWRITEMD::wpid"][::std::mem::offset_of!(FRAMEWRITEMD, wpid) - 8usize];
    ["Offset of field: FRAMEWRITEMD::writetime"]
        [::std::mem::offset_of!(FRAMEWRITEMD, writetime) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SEMFILEDATA {
    pub semdata: sem_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SEMFILEDATA"][::std::mem::size_of::<SEMFILEDATA>() - 32usize];
    ["Alignment of SEMFILEDATA"][::std::mem::align_of::<SEMFILEDATA>() - 8usize];
    ["Offset of field: SEMFILEDATA::semdata"]
        [::std::mem::offset_of!(SEMFILEDATA, semdata) - 0usize];
};

/// This is the one-to-one mapping of the C "IMAGE" struct defined in ImageStruct.h.
/// It was generated using bindgen, so I trust that it's correct. Eventually, this
/// will not be needed in the RUST API, since this object is mostly responsible for
/// storing relevant runtime data, and those can be defined in rust. However, there
/// is an argument for keeping this definition, since it would allow calling external
/// C code from rust that interfaces with an "IMAGE" type, or providing rust-written
/// functions for external C packages to interface with.
///
/// Another option would be to define a trait that composes the C object, and then
/// implement that trait on the rust objects.
///
/// Note that the struct parameter comments/documentation also comes from the C
/// library, so the implied implementation may be slightly different in rust.
///  
/// ## From the C library:
/// The IMAGE structure includes:
/// - an array of IMAGE_KEWORD structures
/// - an array of IMAGE_METADATA structures (usually only 1 element)
///
/// IMPORTANT: memory allocations for dynamically allocated arrays need to be
/// included in the memory size computation in ImageStreamIO_createIm_gpu
#[repr(C)]
#[derive()]
pub struct IMAGE {
    /// local name (can be different from name in shared memory)
    pub name: [::std::os::raw::c_char; 80usize],
    /// Image usage flag
    ///  - 1 if image is used
    ///  - 0 otherwise.
    /// 
    /// This flag is used when an array of IMAGE type is held in memory
    /// as a way to store multiple images.
    ///
    /// When an image is freed, the corresponding memory (in array) is freed
    /// and this flag set to zero.
    ///
    /// The active images can be listed by looking for IMAGE[i].used==1 entries.
    pub used: u8,
    /// increments when image is (re)-created
    pub createcnt: i64,
    /// if shared memory, file descriptor
    pub shmfd: i32,
    /// total size in memory if shared
    pub memsize: u64,
    /// pointer to semaphore for logging  (8 bytes on 64-bit system)
    pub semlog: *mut sem_t,
    /// pointer to image metadata
    pub md: *mut IMAGE_METADATA,
    /// pointer to data array
    pub array: IMAGE__bindgen_ty_1,
    /// array of pointers to semaphores   (each 8 bytes on 64-bit system)
    pub semptr: *mut *mut sem_t,
    /// array of image Keywords
    pub kw: *mut IMAGE_KEYWORD,
    /// array of semfiles
    pub semfile: *mut SEMFILEDATA,
    /// PID of process that read shared memory stream
    /// Initialized at 0. Otherwise, when process is waiting on semaphore, its PID is written in this array
    /// The array can be used to look for available semaphores
    pub semReadPID: *mut pid_t,
    /// PID of processes that are posting the semaphores (JC: I guess there should only be one?)
    pub semWritePID: *mut pid_t,
    /// semaphore control, written by writer to control semaphore behavior.
    /// See SEMAPHORE_CONTROL_XXX defines for details
    pub semctrl: *mut u32,
    /// semaphore status, written by readers to report back to stream what is their current status.
    /// See SEMAPHORE_STATUS_XXX defines for details
    pub semstatus: *mut u32,
    // array to keep track of stream history/depedencies
    pub streamproctrace: *mut STREAM_PROC_TRACE,
    /// flag for each slice if needed (depends on imagetype)
    pub flagarray: *mut u64,
    /// For circular buffer: counter array for circular buffer, copy of cnt0 onto slice index
    pub cntarray: *mut u64,
    /// For each slice index: time at which data was acquires/created.
    /// This time CAN be copied from input to output
    pub atimearray: *mut timespec,
    /// For each slice index: time at which data was written.
    /// This time CAN be copied from input to output
    pub writetimearray: *mut timespec,

    /// Circular Buffer (CB) option
    /// if CBsize>0, recent frames are memcpied in circular buffer
    /// recent frames may be accessed in small CB for logging.
    ///
    /// array of CB metadata
    pub CircBuff_md: *mut CBFRAMEMD,
    /// data storage for circ buffer
    pub CBimdata: *mut ::std::os::raw::c_void,
}
#[doc = " @brief data storage array\n\n The array is declared as a union, so that multiple data types can be supported \\n\n\n For 2D image with pixel indices ii (x-axis) and jj (y-axis), the pixel values are stored as array.<TYPE>[ jj * md[0].size[0] + ii ] \\n\n image md[0].size[0] is x-axis size, md[0].size[1] is y-axis size\n\n For 3D image with pixel indices ii (x-axis), jj (y-axis) and kk (z-axis), the pixel values are stored as array.<TYPE>[ kk * md[0].size[1] * md[0].size[0] + jj * md[0].size[0] + ii ] \\n\n image md[0].size[0] is x-axis size, md[0].size[1] is y-axis size, md[0].size[2] is z-axis size\n\n @note Up to this point, all members of the structure have a fixed memory offset to the start point"]
#[repr(C)]
#[derive(Copy, Clone)]
pub union IMAGE__bindgen_ty_1 {
    pub raw: *mut ::std::os::raw::c_void,
    pub UI8: *mut u8,
    pub SI8: *mut i8,
    pub UI16: *mut u16,
    pub SI16: *mut i16,
    pub UI32: *mut u32,
    pub SI32: *mut i32,
    pub UI64: *mut u64,
    pub SI64: *mut i64,
    pub F: *mut f32,
    pub D: *mut f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE__bindgen_ty_1"][::std::mem::size_of::<IMAGE__bindgen_ty_1>() - 8usize];
    ["Alignment of IMAGE__bindgen_ty_1"][::std::mem::align_of::<IMAGE__bindgen_ty_1>() - 8usize];
    ["Offset of field: IMAGE__bindgen_ty_1::raw"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, raw) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI8"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI8) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI8"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI8) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI16"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI16) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI16"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI16) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI32"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI32) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI32"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI32) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::UI64"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, UI64) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::SI64"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, SI64) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::F"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, F) - 0usize];
    ["Offset of field: IMAGE__bindgen_ty_1::D"]
        [::std::mem::offset_of!(IMAGE__bindgen_ty_1, D) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IMAGE"][::std::mem::size_of::<IMAGE>() - 248usize];
    ["Alignment of IMAGE"][::std::mem::align_of::<IMAGE>() - 8usize];
    ["Offset of field: IMAGE::name"][::std::mem::offset_of!(IMAGE, name) - 0usize];
    ["Offset of field: IMAGE::used"][::std::mem::offset_of!(IMAGE, used) - 80usize];
    ["Offset of field: IMAGE::createcnt"][::std::mem::offset_of!(IMAGE, createcnt) - 88usize];
    ["Offset of field: IMAGE::shmfd"][::std::mem::offset_of!(IMAGE, shmfd) - 96usize];
    ["Offset of field: IMAGE::memsize"][::std::mem::offset_of!(IMAGE, memsize) - 104usize];
    ["Offset of field: IMAGE::semlog"][::std::mem::offset_of!(IMAGE, semlog) - 112usize];
    ["Offset of field: IMAGE::md"][::std::mem::offset_of!(IMAGE, md) - 120usize];
    ["Offset of field: IMAGE::array"][::std::mem::offset_of!(IMAGE, array) - 128usize];
    ["Offset of field: IMAGE::semptr"][::std::mem::offset_of!(IMAGE, semptr) - 136usize];
    ["Offset of field: IMAGE::kw"][::std::mem::offset_of!(IMAGE, kw) - 144usize];
    ["Offset of field: IMAGE::semfile"][::std::mem::offset_of!(IMAGE, semfile) - 152usize];
    ["Offset of field: IMAGE::semReadPID"][::std::mem::offset_of!(IMAGE, semReadPID) - 160usize];
    ["Offset of field: IMAGE::semWritePID"][::std::mem::offset_of!(IMAGE, semWritePID) - 168usize];
    ["Offset of field: IMAGE::semctrl"][::std::mem::offset_of!(IMAGE, semctrl) - 176usize];
    ["Offset of field: IMAGE::semstatus"][::std::mem::offset_of!(IMAGE, semstatus) - 184usize];
    ["Offset of field: IMAGE::streamproctrace"]
        [::std::mem::offset_of!(IMAGE, streamproctrace) - 192usize];
    ["Offset of field: IMAGE::flagarray"][::std::mem::offset_of!(IMAGE, flagarray) - 200usize];
    ["Offset of field: IMAGE::cntarray"][::std::mem::offset_of!(IMAGE, cntarray) - 208usize];
    ["Offset of field: IMAGE::atimearray"][::std::mem::offset_of!(IMAGE, atimearray) - 216usize];
    ["Offset of field: IMAGE::writetimearray"]
        [::std::mem::offset_of!(IMAGE, writetimearray) - 224usize];
    ["Offset of field: IMAGE::CircBuff_md"][::std::mem::offset_of!(IMAGE, CircBuff_md) - 232usize];
    ["Offset of field: IMAGE::CBimdata"][::std::mem::offset_of!(IMAGE, CBimdata) - 240usize];
};
type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __va_list_tag {
    gp_offset: ::std::os::raw::c_uint,
    fp_offset: ::std::os::raw::c_uint,
    overflow_arg_area: *mut ::std::os::raw::c_void,
    reg_save_area: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __va_list_tag"][::std::mem::size_of::<__va_list_tag>() - 24usize];
    ["Alignment of __va_list_tag"][::std::mem::align_of::<__va_list_tag>() - 8usize];
    ["Offset of field: __va_list_tag::gp_offset"]
        [::std::mem::offset_of!(__va_list_tag, gp_offset) - 0usize];
    ["Offset of field: __va_list_tag::fp_offset"]
        [::std::mem::offset_of!(__va_list_tag, fp_offset) - 4usize];
    ["Offset of field: __va_list_tag::overflow_arg_area"]
        [::std::mem::offset_of!(__va_list_tag, overflow_arg_area) - 8usize];
    ["Offset of field: __va_list_tag::reg_save_area"]
        [::std::mem::offset_of!(__va_list_tag, reg_save_area) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
struct __locale_data {
    _address: u8,
}
