name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v26
        with:
          install_url: https://releases.nixos.org/nix/nix-2.34.7/install
      - name: Building package
        run: nix build 
